/*
 * Copyright (c) 2026, 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.oracle.svm.core.libjvm;

import java.io.IOException;
import java.io.PrintWriter;
import java.lang.classfile.ClassFile;
import java.lang.classfile.ClassModel;
import java.lang.classfile.MethodModel;
import java.lang.reflect.AccessFlag;
import java.lang.reflect.Method;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;

import javax.tools.JavaCompiler;
import javax.tools.StandardJavaFileManager;
import javax.tools.ToolProvider;

import org.graalvm.nativeimage.Platform;
import org.graalvm.nativeimage.Platforms;
import org.graalvm.nativeimage.RuntimeOptions;
import org.graalvm.nativeimage.RuntimeOptions.Descriptor;
import org.graalvm.nativeimage.c.function.CEntryPoint;
import org.graalvm.nativeimage.c.function.CEntryPoint.Publish;
import org.graalvm.nativeimage.c.function.CEntryPointLiteral;
import org.graalvm.word.impl.Word;

import com.oracle.svm.core.CPUFeatureAccess;
import com.oracle.svm.core.SubstrateOptions;
import com.oracle.svm.core.SubstrateTarget;
import com.oracle.svm.core.config.ObjectLayout;
import com.oracle.svm.core.cpufeature.RuntimeCPUFeatureCheck;
import com.oracle.svm.core.cpufeature.RuntimeCPUFeatureCheckImpl;
import com.oracle.svm.core.heap.GCCause;
import com.oracle.svm.core.heap.Heap;
import com.oracle.svm.core.hub.DynamicHub;
import com.oracle.svm.core.hub.LayoutEncoding;
import com.oracle.svm.core.jfr.HasJfrSupport;
import com.oracle.svm.core.jni.JNIObjectHandles;
import com.oracle.svm.core.jni.functions.JNIFunctions.Support;
import com.oracle.svm.core.jni.functions.JNIFunctions.Support.JNIEnvEnterFatalOnFailurePrologue;
import com.oracle.svm.core.jni.functions.JNIFunctions.Support.JNIExceptionHandlerReturnFalse;
import com.oracle.svm.core.jni.functions.JNIFunctions.Support.JNIExceptionHandlerReturnNullHandle;
import com.oracle.svm.core.jni.functions.JNIFunctions.Support.JNIExceptionHandlerReturnZero;
import com.oracle.svm.core.jni.functions.JNIFunctions.Support.JNIExceptionHandlerVoid;
import com.oracle.svm.core.jni.headers.JNIEnvironment;
import com.oracle.svm.core.jni.headers.JNIObjectHandle;
import com.oracle.svm.core.log.Log;
import com.oracle.svm.core.os.VirtualMemoryProvider;
import com.oracle.svm.core.thread.ContinuationSupport;
import com.oracle.svm.guest.staging.c.function.CEntryPointOptions;
import com.oracle.svm.shared.Uninterruptible;
import com.oracle.svm.shared.util.ClassUtil;
import com.oracle.svm.shared.util.LogUtils;
import com.oracle.svm.shared.util.VMError;

/// Managed JNI entry points for the WhiteBox API used by JDK test execution.
///
/// Code for implementing more WhiteBox native methods can be generated by
/// [SourceGenerator].
public final class WhiteBoxEntryPoints {

    /// Constants denoting the GC algorithms available in HotSpot.
    /// Keep in sync with the `CollectedHeap::Name` C++ enum in `collectedHeap.hpp`.
    public enum CollectedHeapName {
        None,
        Serial,
        Parallel,
        G1,
        Epsilon,
        Z,
        Shenandoah;
    }

    /// Implemented WhiteBox native methods. Keep sorted.
    private static final WhiteBoxNativeMethod[] WHITE_BOX_NATIVE_METHODS = {
                    method("canWriteJavaHeapArchive", "()Z"),
                    method("fullGC", "()V"),
                    method("getBooleanVMFlag", "(Ljava/lang/String;)Ljava/lang/Boolean;"),
                    method("getCPUFeatures", "()Ljava/lang/String;"),
                    method("getDoubleVMFlag", "(Ljava/lang/String;)Ljava/lang/Double;"),
                    method("getHeapAlignment", "()J"),
                    method("getHeapOopSize", "()I"),
                    method("getHeapSpaceAlignment", "()J"),
                    method("getIntVMFlag", "(Ljava/lang/String;)Ljava/lang/Long;"),
                    method("getIntxVMFlag", "(Ljava/lang/String;)Ljava/lang/Long;"),
                    method("getLibcName", "()Ljava/lang/String;"),
                    method("getObjectAddress0", "(Ljava/lang/Object;)J"),
                    method("getObjectSize0", "(Ljava/lang/Object;)J"),
                    method("getSizeTVMFlag", "(Ljava/lang/String;)Ljava/lang/Long;"),
                    method("getStringVMFlag", "(Ljava/lang/String;)Ljava/lang/String;"),
                    method("getUint64VMFlag", "(Ljava/lang/String;)Ljava/lang/Long;"),
                    method("getUintVMFlag", "(Ljava/lang/String;)Ljava/lang/Long;"),
                    method("getUintxVMFlag", "(Ljava/lang/String;)Ljava/lang/Long;"),
                    method("getVMAllocationGranularity", "()J"),
                    method("getVMPageSize", "()I"),
                    method("hasLibgraal", "()Z"),
                    method("isAsanEnabled", "()Z"),
                    method("isC2OrJVMCIIncluded", "()Z"),
                    method("isCDSIncluded", "()Z"),
                    method("isConstantVMFlag", "(Ljava/lang/String;)Z"),
                    method("isDTraceIncluded", "()Z"),
                    method("isDefaultVMFlag", "(Ljava/lang/String;)Z"),
                    method("isGCSelected", "(I)Z"),
                    method("isGCSelectedErgonomically", "()Z"),
                    method("isGCSupported", "(I)Z"),
                    method("isGCSupportedByJVMCICompiler", "(I)Z"),
                    method("isJFRIncluded", "()Z"),
                    method("isJVMCISupportedByGC", "()Z"),
                    method("isJVMTIIncluded", "()Z"),
                    method("isLockedVMFlag", "(Ljava/lang/String;)Z"),
                    method("isStatic", "()Z"),
                    method("isUbsanEnabled", "()Z"),
                    method("setBooleanVMFlag", "(Ljava/lang/String;Z)V"),
                    method("setDoubleVMFlag", "(Ljava/lang/String;D)V"),
                    method("setIntVMFlag", "(Ljava/lang/String;J)V"),
                    method("setIntxVMFlag", "(Ljava/lang/String;J)V"),
                    method("setSizeTVMFlag", "(Ljava/lang/String;J)V"),
                    method("setStringVMFlag", "(Ljava/lang/String;Ljava/lang/String;)V"),
                    method("setUint64VMFlag", "(Ljava/lang/String;J)V"),
                    method("setUintVMFlag", "(Ljava/lang/String;J)V"),
                    method("setUintxVMFlag", "(Ljava/lang/String;J)V"),
                    method("wordSize", "()J"),
                    method("youngGC", "()V"),
    };

    private WhiteBoxEntryPoints() {
    }

    @Platforms(Platform.HOSTED_ONLY.class)
    private static Method findMethod(String methodName) {
        Method result = null;
        for (Method m : WhiteBoxEntryPoints.class.getDeclaredMethods()) {
            if (m.getName().equals(methodName)) {
                VMError.guarantee(result == null, "multiple definitions found: %s and %s", result, m);
                result = m;
            }
        }
        VMError.guarantee(result != null, "could not find method %s in %s", methodName, WhiteBoxEntryPoints.class);
        return result;
    }

    /// Creates a WhiteBox native method descriptor and its managed JNI entry point.
    @Platforms(Platform.HOSTED_ONLY.class)
    private static WhiteBoxNativeMethod method(String name, String signature) {
        Method declaredMethod = findMethod(name);
        CEntryPointLiteral<?> entryPoint = CEntryPointLiteral.create(WhiteBoxEntryPoints.class, name, declaredMethod.getParameterTypes());
        return new WhiteBoxNativeMethod(name, signature, entryPoint);
    }

    /// Describes one native method registered by `WhiteBox.registerNatives`.
    private record WhiteBoxNativeMethod(String name, String signature, CEntryPointLiteral<?> entryPoint) {
    }

    /// JNI linkage symbol for [#registerNatives].
    public static final String WHITEBOX_REGISTER_NATIVES_SYMBOL = "Java_jdk_test_whitebox_WhiteBox_registerNatives";

    /// Entry point address for [#registerNatives].
    public static final CEntryPointLiteral<?> WHITEBOX_REGISTER_NATIVES = CEntryPointLiteral.create(WhiteBoxEntryPoints.class, "registerNatives", JNIEnvironment.class, JNIObjectHandle.class);

    @CEntryPoint(exceptionHandler = JNIExceptionHandlerVoid.class, name = WHITEBOX_REGISTER_NATIVES_SYMBOL, publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static void registerNatives(@SuppressWarnings("unused") JNIEnvironment env, JNIObjectHandle clazz) {
        Class<?> whiteBoxClass = JNIObjectHandles.getObject(clazz);
        if (!SubstrateOptions.WhiteBoxAPI.getValue() || whiteBoxClass.getClassLoader() != null) {
            throw new UnsatisfiedLinkError("WhiteBox native methods are only available for the boot-loaded WhiteBox class when -XX:+WhiteBoxAPI is enabled");
        }
        DynamicHub declaringClass = DynamicHub.fromClass(JNIObjectHandles.getObject(clazz));
        WhiteBoxNativeMethod[] methods = WHITE_BOX_NATIVE_METHODS;
        for (int i = 0; i < methods.length; i++) {
            WhiteBoxNativeMethod method = methods[i];
            try {
                Support.registerNative(declaringClass, method.name(), method.signature(), i, method.entryPoint().getFunctionPointer(), true);
            } catch (NoSuchMethodError e) {
                // NoSuchMethodError is thrown when a method can't be found or a method is not native.
                // Ignore the exception since it is not preventing use of other WhiteBox methods.
                // This mimics HotSpot behavior.
                LogUtils.warning(e.toString());
            }
        }
    }

    /// Reports whether `nameHandle` denotes a constant runtime option.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnFalse.class, name = "Java_jdk_test_whitebox_WhiteBox_isConstantVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static boolean isConstantVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle) {
        // Checks for flag existence.
        getDescriptor(nameHandle, Object.class);
        // SVM does not have constant runtime flags.
        return false;
    }

    /// Reports whether `nameHandle` still has its default runtime option value.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnFalse.class, name = "Java_jdk_test_whitebox_WhiteBox_isDefaultVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static boolean isDefaultVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle) {
        Descriptor descriptor = getDescriptor(nameHandle, Object.class);
        if (descriptor == null) {
            return false;
        }
        return Objects.equals(getRuntimeOption(descriptor.name()), descriptor.defaultValue());
    }

    /// Reports whether `nameHandle` denotes a locked runtime option.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnFalse.class, name = "Java_jdk_test_whitebox_WhiteBox_isLockedVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static boolean isLockedVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle) {
        // Checks for flag existence.
        getDescriptor(nameHandle, Object.class);
        // SVM does not have locked runtime flags.
        return false;
    }

    /// Sets a boolean runtime option from a HotSpot WhiteBox VM flag.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerVoid.class, name = "Java_jdk_test_whitebox_WhiteBox_setBooleanVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static void setBooleanVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle, boolean value) {
        setRuntimeOption(nameHandle, value);
    }

    /// Sets an integer runtime option from a HotSpot WhiteBox VM flag.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerVoid.class, name = "Java_jdk_test_whitebox_WhiteBox_setIntVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static void setIntVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle, long value) {
        setRuntimeOption(nameHandle, value);
    }

    /// Sets an unsigned integer runtime option from a HotSpot WhiteBox VM flag.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerVoid.class, name = "Java_jdk_test_whitebox_WhiteBox_setUintVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static void setUintVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle, long value) {
        setRuntimeOption(nameHandle, value);
    }

    /// Sets an `intx` runtime option from a HotSpot WhiteBox VM flag.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerVoid.class, name = "Java_jdk_test_whitebox_WhiteBox_setIntxVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static void setIntxVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle, long value) {
        setRuntimeOption(nameHandle, value);
    }

    /// Sets a `uintx` runtime option from a HotSpot WhiteBox VM flag.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerVoid.class, name = "Java_jdk_test_whitebox_WhiteBox_setUintxVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static void setUintxVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle, long value) {
        setRuntimeOption(nameHandle, value);
    }

    /// Sets a 64-bit unsigned runtime option from a HotSpot WhiteBox VM flag.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerVoid.class, name = "Java_jdk_test_whitebox_WhiteBox_setUint64VMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static void setUint64VMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle, long value) {
        setRuntimeOption(nameHandle, value);
    }

    /// Sets a `size_t` runtime option from a HotSpot WhiteBox VM flag.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerVoid.class, name = "Java_jdk_test_whitebox_WhiteBox_setSizeTVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static void setSizeTVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle, long value) {
        setRuntimeOption(nameHandle, value);
    }

    /// Sets a string runtime option from a HotSpot WhiteBox VM flag.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerVoid.class, name = "Java_jdk_test_whitebox_WhiteBox_setStringVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static void setStringVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle, JNIObjectHandle valueHandle) {
        setRuntimeOption(nameHandle, JNIObjectHandles.getObject(valueHandle));
    }

    /// Sets a double runtime option from a HotSpot WhiteBox VM flag.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerVoid.class, name = "Java_jdk_test_whitebox_WhiteBox_setDoubleVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static void setDoubleVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle, double value) {
        setRuntimeOption(nameHandle, value);
    }

    /// Gets a boolean runtime option as a HotSpot WhiteBox VM flag.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnNullHandle.class, name = "Java_jdk_test_whitebox_WhiteBox_getBooleanVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static JNIObjectHandle getBooleanVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle) {
        String name = Objects.requireNonNull(JNIObjectHandles.getObject(nameHandle));
        Boolean value = switch (name) {
            case "VMContinuations" -> ContinuationSupport.isSupported();
            case "UseCompiler", "ProfileInterpreter" -> getOption("JITEnableCompilation", Boolean.class, false);
            case "UseJVMCICompiler" -> true;
            default -> null;
        };
        return value != null ? JNIObjectHandles.createLocal(value) : getRuntimeOption(nameHandle, Boolean.class);
    }

    /// Gets an integer runtime option as a HotSpot WhiteBox VM flag.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnNullHandle.class, name = "Java_jdk_test_whitebox_WhiteBox_getIntVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static JNIObjectHandle getIntVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle) {
        return getLongRuntimeOption(nameHandle);
    }

    /// Gets an unsigned integer runtime option as a HotSpot WhiteBox VM flag.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnNullHandle.class, name = "Java_jdk_test_whitebox_WhiteBox_getUintVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static JNIObjectHandle getUintVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle) {
        return getLongRuntimeOption(nameHandle);
    }

    /// Gets an `intx` runtime option as a HotSpot WhiteBox VM flag.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnNullHandle.class, name = "Java_jdk_test_whitebox_WhiteBox_getIntxVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static JNIObjectHandle getIntxVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle) {
        return getLongRuntimeOption(nameHandle);
    }

    /// Gets a `uintx` runtime option as a HotSpot WhiteBox VM flag.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnNullHandle.class, name = "Java_jdk_test_whitebox_WhiteBox_getUintxVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static JNIObjectHandle getUintxVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle) {
        return getLongRuntimeOption(nameHandle);
    }

    /// Gets a 64-bit unsigned runtime option as a HotSpot WhiteBox VM flag.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnNullHandle.class, name = "Java_jdk_test_whitebox_WhiteBox_getUint64VMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static JNIObjectHandle getUint64VMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle) {
        return getLongRuntimeOption(nameHandle);
    }

    /// Gets a `size_t` runtime option as a HotSpot WhiteBox VM flag.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnNullHandle.class, name = "Java_jdk_test_whitebox_WhiteBox_getSizeTVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static JNIObjectHandle getSizeTVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle) {
        return getLongRuntimeOption(nameHandle);
    }

    /// Gets a string runtime option as a HotSpot WhiteBox VM flag.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnNullHandle.class, name = "Java_jdk_test_whitebox_WhiteBox_getStringVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static JNIObjectHandle getStringVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle) {
        return getRuntimeOption(nameHandle, String.class);
    }

    /// Gets a double runtime option as a HotSpot WhiteBox VM flag.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnNullHandle.class, name = "Java_jdk_test_whitebox_WhiteBox_getDoubleVMFlag", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static JNIObjectHandle getDoubleVMFlag(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle nameHandle) {
        return getRuntimeOption(nameHandle, Double.class);
    }

    /// Gets the descriptor for the runtime option named by `nameHandle`.
    ///
    /// If the option does not exist or is not of type `type`, null is returned
    /// *and* a warning is logged. HotSpot's WhiteBox functions for accessing
    /// options do not issue a warning. However, SVM does not
    /// have support for JEP 358 ("Helpful NullPointerExceptions"), so it can be
    /// hard to know whether an NPE is due to a missing option or an attempt
    /// to access an existing option with the wrong type.
    private static Descriptor getDescriptor(JNIObjectHandle nameHandle, Class<?> type) {
        String name = JNIObjectHandles.getObject(nameHandle);
        Descriptor descriptor = RuntimeOptions.getDescriptor(name);
        if (descriptor == null) {
            warn("Unknown option: " + name);
            return null;
        } else if (!isExpectedType(type, descriptor.valueType())) {
            warn("Expected " + ClassUtil.getUnqualifiedName(type) + " option, got " + ClassUtil.getUnqualifiedName(descriptor.valueType()) + " option: " + name);
            return null;
        }
        return descriptor;
    }

    /// Reports whether `actualType` is compatible with the WhiteBox accessor for `expectedType`.
    private static boolean isExpectedType(Class<?> expectedType, Class<?> actualType) {
        if (expectedType == Object.class) {
            return true;
        }
        if (expectedType == Number.class) {
            // Runtime option numbers use boxed primitive types.
            return actualType == Byte.class || actualType == Short.class || actualType == Integer.class || actualType == Long.class || actualType == Float.class || actualType == Double.class;
        }
        return expectedType == actualType;
    }

    /// Gets the current runtime option value for `name`.
    private static Object getRuntimeOption(String name) {
        try {
            return RuntimeOptions.get(name);
        } catch (RuntimeException e) {
            return null;
        }
    }

    /// Gets a runtime option value with a fallback for WhiteBox aliases.
    private static <T> T getOption(String name, Class<T> requiredType, T defaultValue) {
        Descriptor descriptor = RuntimeOptions.getDescriptor(name);
        if (descriptor == null) {
            if (defaultValue != null) {
                return defaultValue;
            }
            throw new RuntimeException("Unknown option: " + name);
        }

        if (!isExpectedType(requiredType, descriptor.valueType())) {
            throw new RuntimeException("Option " + name + " is of type " + descriptor.valueType() + ", not " + requiredType);
        }
        return RuntimeOptions.get(descriptor.name());
    }

    private static void warn(String msg) {
        Log.log().string("Substrate VM warning: [WhiteBox] ").string(msg).newline();
    }

    /// Gets the runtime option named by `nameHandle` if it has type `type`.
    private static JNIObjectHandle getRuntimeOption(JNIObjectHandle nameHandle, Class<?> type) {
        Descriptor descriptor = getDescriptor(nameHandle, type);
        if (descriptor == null) {
            return JNIObjectHandles.nullHandle();
        }
        Object value = getRuntimeOption(descriptor.name());
        return JNIObjectHandles.createLocal(value);
    }

    /// Gets the numeric runtime option named by `nameHandle` as a boxed `long`.
    private static JNIObjectHandle getLongRuntimeOption(JNIObjectHandle nameHandle) {
        Descriptor descriptor = getDescriptor(nameHandle, Number.class);
        if (descriptor == null) {
            return JNIObjectHandles.nullHandle();
        }
        Object value = getRuntimeOption(descriptor.name());
        return value instanceof Number number ? JNIObjectHandles.createLocal(number.longValue()) : JNIObjectHandles.nullHandle();
    }

    /// Sets the runtime option named by `nameHandle` to `value`.
    private static void setRuntimeOption(JNIObjectHandle nameHandle, Object value) {
        Class<?> type = value == null ? Object.class : value.getClass();
        Descriptor descriptor = getDescriptor(nameHandle, type);
        if (descriptor == null || value == null) {
            return;
        }
        Object convertedValue = convertValue(descriptor, value);
        if (convertedValue != null) {
            try {
                RuntimeOptions.set(descriptor.name(), convertedValue);
            } catch (RuntimeException e) {
                // WhiteBox setters silently ignore flags that cannot be updated in Crema.
            }
        }
    }

    /// Converts `value` to the Java type expected by `descriptor`.
    private static Object convertValue(Descriptor descriptor, Object value) {
        if (descriptor.valueType().isInstance(value)) {
            return value;
        }
        try {
            return descriptor.convertValue(value.toString());
        } catch (IllegalArgumentException e) {
            return null;
        }
    }

    /// Reports the HotSpot CPU feature string expected by WhiteBox tests.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnNullHandle.class, name = "Java_jdk_test_whitebox_WhiteBox_getCPUFeatures", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static JNIObjectHandle getCPUFeatures(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        Set<String> featureNames = new TreeSet<>();
        for (Enum<?> feature : CPUFeatureAccess.singleton().buildtimeCPUFeatures()) {
            featureNames.add(feature.name());
        }
        RuntimeCPUFeatureCheckImpl runtimeFeatureCheck = RuntimeCPUFeatureCheckImpl.runtimeLastLayer();
        for (Enum<?> feature : RuntimeCPUFeatureCheck.getSupportedFeatures(SubstrateTarget.getArchitecture())) {
            if (runtimeFeatureCheck.isAvailableAtRuntime(feature)) {
                featureNames.add(feature.name());
            }
        }
        return JNIObjectHandles.createLocal(String.join(",", featureNames));
    }

    /// Gets the virtual memory page size as a HotSpot WhiteBox value.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnZero.class, name = "Java_jdk_test_whitebox_WhiteBox_getVMPageSize", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static int getVMPageSize(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        return (int) VirtualMemoryProvider.get().getGranularity().rawValue();
    }

    /// Gets the heap reference size as a HotSpot WhiteBox value.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnZero.class, name = "Java_jdk_test_whitebox_WhiteBox_getHeapOopSize", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static int getHeapOopSize(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        return ObjectLayout.singleton().getReferenceSize();
    }

    /// Gets the virtual-memory allocation granularity as a HotSpot WhiteBox value.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnZero.class, name = "Java_jdk_test_whitebox_WhiteBox_getVMAllocationGranularity", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static long getVMAllocationGranularity(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        return VirtualMemoryProvider.get().getGranularity().rawValue();
    }

    /// Gets the SVM object alignment as a HotSpot WhiteBox heap-space alignment value.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnZero.class, name = "Java_jdk_test_whitebox_WhiteBox_getHeapSpaceAlignment", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static long getHeapSpaceAlignment(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        return ObjectLayout.singleton().getAlignment();
    }

    /// Gets the SVM object alignment as a HotSpot WhiteBox heap alignment value.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnZero.class, name = "Java_jdk_test_whitebox_WhiteBox_getHeapAlignment", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static long getHeapAlignment(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        return ObjectLayout.singleton().getAlignment();
    }

    /// Gets the current native address of the object represented by `objectHandle`.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnZero.class, name = "Java_jdk_test_whitebox_WhiteBox_getObjectAddress0", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static long getObjectAddress0(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle objectHandle) {
        return Word.objectToUntrackedPointer(JNIObjectHandles.getObject(objectHandle)).rawValue();
    }

    /// Gets the current allocation size of the object represented by `objectHandle`.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnZero.class, name = "Java_jdk_test_whitebox_WhiteBox_getObjectSize0", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    @Uninterruptible(reason = "Prevent a GC moving the object or interfering with its identity hash state.")
    static long getObjectSize0(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, JNIObjectHandle objectHandle) {
        return LayoutEncoding.getSizeFromObject(JNIObjectHandles.getObject(objectHandle)).rawValue();
    }

    /// Gets the SVM word size as a HotSpot WhiteBox value.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnZero.class, name = "Java_jdk_test_whitebox_WhiteBox_wordSize", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static long wordSize(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        return SubstrateTarget.getWordSize();
    }

    /// Requests the SVM garbage collector to perform a collection.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerVoid.class, name = "Java_jdk_test_whitebox_WhiteBox_youngGC", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static void youngGC(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        Heap.getHeap().getGC().collect(GCCause.UnitTest);
    }

    /// Requests the SVM garbage collector to perform a complete collection.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerVoid.class, name = "Java_jdk_test_whitebox_WhiteBox_fullGC", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static void fullGC(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        Heap.getHeap().getGC().collectCompletely(GCCause.UnitTest);
    }

    /// Reports whether C2 or JVMCI support is included in the VM.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnFalse.class, name = "Java_jdk_test_whitebox_WhiteBox_isC2OrJVMCIIncluded", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static boolean isC2OrJVMCIIncluded(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        return true;
    }

    /// Reports whether JVMCI is supported by the selected garbage collector.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnFalse.class, name = "Java_jdk_test_whitebox_WhiteBox_isJVMCISupportedByGC", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static boolean isJVMCISupportedByGC(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        return true;
    }

    /// Reports whether Class Data Sharing support is included.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnFalse.class, name = "Java_jdk_test_whitebox_WhiteBox_isCDSIncluded", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static boolean isCDSIncluded(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        return false;
    }

    /// Reports whether Java Flight Recorder support is included.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnFalse.class, name = "Java_jdk_test_whitebox_WhiteBox_isJFRIncluded", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static boolean isJFRIncluded(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        return HasJfrSupport.get();
    }

    /// Reports whether DTrace support is included.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnFalse.class, name = "Java_jdk_test_whitebox_WhiteBox_isDTraceIncluded", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static boolean isDTraceIncluded(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        return false;
    }

    /// Reports whether this VM can write Java heap archives.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnFalse.class, name = "Java_jdk_test_whitebox_WhiteBox_canWriteJavaHeapArchive", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static boolean canWriteJavaHeapArchive(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        return false;
    }

    /// Reports whether JVMTI support is included.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnFalse.class, name = "Java_jdk_test_whitebox_WhiteBox_isJVMTIIncluded", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static boolean isJVMTIIncluded(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        return SubstrateOptions.JVMTI.getValue();
    }

    /// Determines whether the HotSpot GC id `hsName` denotes the single GC
    /// configured at build time.
    private static boolean isHeapGC(int hsName) {
        String gcName = Heap.getHeap().getGC().getName();
        if (gcName.endsWith(" GC")) {
            gcName = gcName.substring(0, gcName.length() - 3);
        }
        for (var gc : CollectedHeapName.values()) {
            if (gc.ordinal() == hsName) {
                return gc.name().equals(gcName);
            }
        }
        return false;
    }

    /// Reports whether the HotSpot GC id `name` is supported.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnFalse.class, name = "Java_jdk_test_whitebox_WhiteBox_isGCSupported", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static boolean isGCSupported(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, int name) {
        return isHeapGC(name);
    }

    /// Reports whether the HotSpot GC id `name` is supported by the JVMCI compiler.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnFalse.class, name = "Java_jdk_test_whitebox_WhiteBox_isGCSupportedByJVMCICompiler", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static boolean isGCSupportedByJVMCICompiler(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, @SuppressWarnings("unused") int name) {
        return isHeapGC(name);
    }

    /// Reports whether the HotSpot GC id `name` is currently selected.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnFalse.class, name = "Java_jdk_test_whitebox_WhiteBox_isGCSelected", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static boolean isGCSelected(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self, int name) {
        return isHeapGC(name);
    }

    /// Reports whether the selected garbage collector was chosen ergonomically.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnFalse.class, name = "Java_jdk_test_whitebox_WhiteBox_isGCSelectedErgonomically", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static boolean isGCSelectedErgonomically(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        // The SVM GC is never selected ergonomically as it's selected at build time.
        return false;
    }

    /// Reports whether the VM was built with AddressSanitizer.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnFalse.class, name = "Java_jdk_test_whitebox_WhiteBox_isAsanEnabled", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static boolean isAsanEnabled(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        return false;
    }

    /// Reports whether the VM was built with UndefinedBehaviorSanitizer.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnFalse.class, name = "Java_jdk_test_whitebox_WhiteBox_isUbsanEnabled", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static boolean isUbsanEnabled(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        return false;
    }

    /// Reports whether libgraal is available.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnFalse.class, name = "Java_jdk_test_whitebox_WhiteBox_hasLibgraal", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static boolean hasLibgraal(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        return false;
    }

    /// Reports whether the VM is a statically linked image.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnFalse.class, name = "Java_jdk_test_whitebox_WhiteBox_isStatic", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static boolean isStatic(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        // This is exposed as the `jdk.requires` property for `@requires` clauses in jtreg tests.
        // It's mainly used to disable JNI invocation tests. These tests should be run on crema.
        return false;
    }

    /// Gets the libc name reported through the WhiteBox API.
    @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnNullHandle.class, name = "Java_jdk_test_whitebox_WhiteBox_getLibcName", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)
    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)
    static JNIObjectHandle getLibcName(@SuppressWarnings("unused") JNIEnvironment env, @SuppressWarnings("unused") JNIObjectHandle self) {
        return JNIObjectHandles.createLocal("default");
    }

    /// Generates paste-ready source code for WhiteBox native methods that are not yet implemented.
    ///
    /// ```
    /// mx -p substratevm build
    /// mx -p substratevm vm -cp @com.oracle.svm.core com.oracle.svm.core.libjvm.WhiteBoxEntryPoints$SourceGenerator /path/to/labsjdk-ce
    /// ```
    @Platforms(Platform.HOSTED_ONLY.class)
    public static final class SourceGenerator {
        private static final String WHITEBOX_SOURCE = "jdk/test/whitebox/WhiteBox.java";

        private SourceGenerator() {
        }

        /// Compiles the WhiteBox source in the JDK repository passed through `args` and prints native entry-point stubs.
        public static void main(String[] args) throws IOException {
            if (args.length != 1) {
                throw new IllegalArgumentException("Usage: SourceGenerator <jdk-repository>");
            }
            Path baseDirectory = Path.of(args[0]).resolve("test/lib");
            Path sourceFile = baseDirectory.resolve(WHITEBOX_SOURCE);
            if (!Files.isRegularFile(sourceFile)) {
                throw new IOException("WhiteBox source file does not exist: " + sourceFile);
            }

            JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
            if (compiler == null) {
                throw new IllegalStateException("A JDK compiler is required");
            }
            Path outputDirectory = Files.createTempDirectory("whitebox-class-");
            try {
                try (StandardJavaFileManager fileManager = compiler.getStandardFileManager(null, null, null)) {
                    Iterable<? extends javax.tools.JavaFileObject> compilationUnits = fileManager.getJavaFileObjects(sourceFile.toFile());
                    List<String> options = List.of("--source-path", baseDirectory.toString(), "-d", outputDirectory.toString());
                    boolean compiled = compiler.getTask(new PrintWriter(System.out, true), fileManager, null, options, null, compilationUnits).call();
                    if (!compiled) {
                        throw new IllegalStateException("Could not compile " + sourceFile);
                    }
                }

                Path classFile = outputDirectory.resolve("jdk/test/whitebox/WhiteBox.class");
                ClassModel classModel = ClassFile.of().parse(Files.readAllBytes(classFile));
                Set<String> existingMethods = existingWhiteBoxMethods();
                List<MethodModel> methods = classModel.methods().stream() //
                                .filter(method -> method.flags().has(AccessFlag.NATIVE)) //
                                .filter(method -> !existingMethods.contains(method.methodName().stringValue())) //
                                .sorted(Comparator.comparing(m -> m.methodName().stringValue())) //
                                .toList();
                System.out.println();
                System.out.println("--- Entries to add to WHITE_BOX_NATIVE_METHODS initializer ---");
                System.out.println();
                for (var method : methods) {
                    System.out.println("                    method(\"" + method.methodName().stringValue() + "\", \"" + method.methodType().stringValue() + "\"),");
                }
                System.out.println();
                System.out.println("--- @CEntryPoint methods ---");
                System.out.println();
                for (var method : methods) {
                    printStub(method.methodName().stringValue(), method.methodType().stringValue());
                }
            } finally {
                deleteRecursively(outputDirectory);
            }
        }

        /// Finds WhiteBox native names that already have a C entry point.
        private static Set<String> existingWhiteBoxMethods() {
            String prefix = "Java_jdk_test_whitebox_WhiteBox_";
            Set<String> result = new HashSet<>();
            for (Method method : WhiteBoxEntryPoints.class.getDeclaredMethods()) {
                // Checkstyle: allow direct annotation access
                CEntryPoint entryPoint = method.getAnnotation(CEntryPoint.class);
                // Checkstyle: disallow direct annotation access
                if (entryPoint != null && entryPoint.name().startsWith(prefix)) {
                    result.add(entryPoint.name().substring(prefix.length()));
                }
            }
            return result;
        }

        /// Prints a placeholder C entry-point stub for a native method in the compiled WhiteBox class.
        private static void printStub(String methodName, String descriptor) {
            List<String> parameterTypes = parseParameterTypes(descriptor);
            String returnType = parseReturnType(descriptor);
            String exceptionHandler = exceptionHandler(returnType);

            System.out.println("    @CEntryPoint(exceptionHandler = " + exceptionHandler + ".class, name = \"Java_jdk_test_whitebox_WhiteBox_" + methodName +
                            "\", publishAs = Publish.NotPublished, include = LibJVMSupport.Enabled.class)");
            System.out.println("    @CEntryPointOptions(prologue = JNIEnvEnterFatalOnFailurePrologue.class)");
            StringBuilder declaration = new StringBuilder("    static ").append(returnType).append(' ').append(methodName).append(
                            "(@SuppressWarnings(\"unused\") JNIEnvironment env, @SuppressWarnings(\"unused\") JNIObjectHandle self");
            for (int i = 0; i < parameterTypes.size(); i++) {
                declaration.append(", @SuppressWarnings(\"unused\") ").append(parameterTypes.get(i)).append(" arg").append(i);
            }
            declaration.append(") {");
            System.out.println(declaration);
            System.out.println("        // TODO");
            System.out.println("    }");
            System.out.println();
        }

        /// Parses parameter types from a JVM method descriptor.
        private static List<String> parseParameterTypes(String descriptor) {
            List<String> result = new java.util.ArrayList<>();
            int index = 1;
            while (descriptor.charAt(index) != ')') {
                ParsedType type = parseType(descriptor, index);
                result.add(type.javaType());
                index = type.nextIndex();
            }
            return result;
        }

        /// Parses the return type from a JVM method descriptor.
        private static String parseReturnType(String descriptor) {
            int index = descriptor.indexOf(')') + 1;
            return parseType(descriptor, index).javaType();
        }

        /// Parses one JVM descriptor type and returns the next descriptor index.
        private static ParsedType parseType(String descriptor, int startIndex) {
            char kind = descriptor.charAt(startIndex);
            if (kind == '[' || kind == 'L') {
                int endIndex = startIndex;
                while (descriptor.charAt(endIndex) == '[') {
                    endIndex++;
                }
                if (descriptor.charAt(endIndex) == 'L') {
                    endIndex = descriptor.indexOf(';', endIndex);
                }
                return new ParsedType("JNIObjectHandle", endIndex + 1);
            }
            String javaType = switch (kind) {
                case 'Z' -> "boolean";
                case 'B' -> "byte";
                case 'C' -> "char";
                case 'S' -> "short";
                case 'I' -> "int";
                case 'J' -> "long";
                case 'F' -> "float";
                case 'D' -> "double";
                case 'V' -> "void";
                default -> throw new IllegalArgumentException("Unknown JVM descriptor type: " + kind);
            };
            return new ParsedType(javaType, startIndex + 1);
        }

        /// Selects the JNI exception handler for a generated return type.
        private static String exceptionHandler(String returnType) {
            return switch (returnType) {
                case "void" -> "JNIExceptionHandlerVoid";
                case "boolean" -> "JNIExceptionHandlerReturnFalse";
                case "int", "long" -> "JNIExceptionHandlerReturnZero";
                default -> "JNIExceptionHandlerReturnNullHandle";
            };
        }

        private record ParsedType(String javaType, int nextIndex) {
        }

        /// Deletes a temporary directory and its contents.
        private static void deleteRecursively(Path directory) throws IOException {
            try (var paths = Files.walk(directory)) {
                for (Path path : paths.sorted(Comparator.reverseOrder()).toList()) {
                    Files.deleteIfExists(path);
                }
            }
        }
    }
}
