/*
 * Copyright (c) 2018, 2023, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
package com.oracle.svm.core.graal.llvm.util;

import static com.oracle.svm.shared.util.VMError.shouldNotReachHere;

import java.nio.ByteBuffer;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import org.graalvm.collections.EconomicSet;

import com.oracle.svm.core.SubstrateTarget;
import com.oracle.svm.shadowed.org.bytedeco.llvm.LLVM.LLVMRelocationIteratorRef;
import com.oracle.svm.shadowed.org.bytedeco.llvm.LLVM.LLVMSectionIteratorRef;
import com.oracle.svm.shadowed.org.bytedeco.llvm.global.LLVM;
import jdk.graal.compiler.core.common.NumUtil;

/**
 * Parses the LLVM stack map section emitted for calls and stackmaps generated by the LLVM backend.
 * Native Image uses the resulting data to recover frame sizes and to build {@link
 * com.oracle.svm.core.heap.SubstrateReferenceMap reference maps} for safepoints after LLVM has
 * optimized and lowered the bitcode.
 * <p>
 * LLVM's {@code rewrite-statepoints-for-gc} pass records every live tracked pointer as a
 * base/reference pair in the stack map. The base is the object pointer that keeps the object alive;
 * the reference can either be the same stack slot or a derived reference that points into the
 * object's interior. {@link #forEachStatepointOffset} translates these pairs into stack offsets and
 * reports the derived-reference slot together with its base slot.
 * <p>
 * Compressed Java references need one additional piece of information because LLVM stack map
 * locations do not directly preserve the LLVM pointer address space. The Native Image LLVM patch
 * for compressed pointers therefore stores the live {@code addrspace(2)} values in the statepoint's
 * deopt-argument section. In the stack map location list, those entries appear immediately after
 * the three statepoint header locations and before the base/reference pairs. This class treats them
 * as the set of stack slots that store compressed references and uses that set to determine the
 * {@code compressed} flag passed to the callback.
 */
public class LLVMStackMapInfo {
    public static final long DEFAULT_PATCHPOINT_ID = 0xABCDEF00L;

    static class StackMap {
        byte version;
        Function[] functions;
        long[] constants;
    }

    static class Function {
        long address;
        long stackSize;
        Record[] records;
    }

    static class Record {
        long patchpointID;
        int instructionOffset;
        short flags;
        Location[] locations;
        LiveOut[] liveOuts;
    }

    static class Location {
        Type type;
        short size;
        short regNum;
        int offset;

        enum Type {
            Register(1),
            Direct(2),
            Indirect(3),
            Constant(4),
            ConstantIndex(5);

            private final byte encoding;

            Type(int encoding) {
                this.encoding = (byte) encoding;
            }

            static Type decode(byte encoding) {
                for (Type type : values()) {
                    if (type.encoding == encoding) {
                        return type;
                    }
                }
                return null;
            }
        }
    }

    static class LiveOut {
        short regNum;
        byte size;
    }

    /*
     * Stack map format specification available at
     * https://llvm.org/docs/StackMaps.html#stack-map-format
     */
    LLVMStackMapInfo(ByteBuffer buffer, LLVMSectionIteratorRef relocationsSectionIteratorRef) {
        LLVMRelocationIteratorRef relocationIteratorRef = LLVM.LLVMGetRelocations(relocationsSectionIteratorRef);
        StackMap stackMap = new StackMap();

        int offset = 0;

        stackMap.version = buffer.get(offset);
        offset += Byte.BYTES;

        // skip header
        offset += Byte.BYTES;
        offset += Short.BYTES;

        stackMap.functions = new Function[buffer.getInt(offset)];
        offset += Integer.BYTES;

        stackMap.constants = new long[buffer.getInt(offset)];
        offset += Integer.BYTES;

        int numRecords = buffer.getInt(offset);
        offset += Integer.BYTES;

        long totalNumRecords = 0L;
        for (int i = 0; i < stackMap.functions.length; i++) {
            Function function = new Function();

            function.address = buffer.getLong(offset); // always 0
            offset += Long.BYTES;

            function.stackSize = buffer.getLong(offset);
            offset += Long.BYTES;

            function.records = new Record[NumUtil.safeToInt(buffer.getLong(offset))];
            offset += Long.BYTES;

            stackMap.functions[i] = function;

            totalNumRecords += function.records.length;
        }

        for (int i = 0; i < stackMap.constants.length; ++i) {
            stackMap.constants[i] = buffer.getLong(offset);
            offset += Long.BYTES;
        }

        int fun = 0;
        int rec = 0;
        assert numRecords == totalNumRecords;
        for (int i = 0; i < numRecords; ++i, ++rec) {
            while (rec == stackMap.functions[fun].records.length) {
                fun++;
                rec = 0;
            }

            Function function = stackMap.functions[fun];
            Record record = new Record();

            record.patchpointID = buffer.getLong(offset);
            offset += Long.BYTES;

            record.instructionOffset = LLVMTargetSpecific.get().getInstructionOffset(buffer, offset, relocationsSectionIteratorRef, relocationIteratorRef);
            offset += Integer.BYTES;

            record.flags = buffer.getShort(offset);
            offset += Short.BYTES;

            record.locations = new Location[buffer.getShort(offset)];
            offset += Short.BYTES;

            for (int j = 0; j < record.locations.length; j++) {
                Location location = new Location();

                location.type = Location.Type.decode(buffer.get(offset));
                offset += Byte.BYTES;
                offset += Byte.BYTES; // skip reserved bytes

                location.size = buffer.getShort(offset);
                offset += Short.BYTES;

                location.regNum = buffer.getShort(offset);
                offset += Short.BYTES;
                offset += Short.BYTES; // skip reserved bytes

                location.offset = buffer.getInt(offset);
                offset += Integer.BYTES;

                record.locations[j] = location;
            }
            if (offset % Long.BYTES != 0) {
                offset += Integer.BYTES; // skip alignment padding
            }
            offset += Short.BYTES; // skip padding

            record.liveOuts = new LiveOut[buffer.getShort(offset)];
            offset += Short.BYTES;

            for (int j = 0; j < record.liveOuts.length; j++) {
                LiveOut liveOut = new LiveOut();

                liveOut.regNum = buffer.getShort(offset);
                offset += Short.BYTES;
                offset += Byte.BYTES; // skip reserved bytes

                liveOut.size = buffer.get(offset);
                offset += Byte.BYTES;

                record.liveOuts[j] = liveOut;
            }
            if (offset % Long.BYTES != 0) {
                offset += Integer.BYTES; // skip alignment padding
            }

            function.records[rec] = record;

            if (patchpointToFunction.containsKey(record.patchpointID)) {
                assert record.patchpointID == DEFAULT_PATCHPOINT_ID || patchpointToFunction.get(record.patchpointID) == function;
            }
            patchpointToFunction.put(record.patchpointID, function);
            patchpointsByID.computeIfAbsent(record.patchpointID, _ -> new HashSet<>()).add(record); // noEconomicSet(streaming)
        }

        LLVM.LLVMDisposeRelocationIterator(relocationIteratorRef);
    }

    private Map<Long, Function> patchpointToFunction = new HashMap<>();
    private Map<Long, Set<Record>> patchpointsByID = new HashMap<>(); // noEconomicSet(streaming)

    long getFunctionStackSize(long startPatchpointID) {
        assert patchpointToFunction.containsKey(startPatchpointID);
        return patchpointToFunction.get(startPatchpointID).stackSize;
    }

    private long getFunctionOffset(long startPatchpointID) {
        assert patchpointToFunction.containsKey(startPatchpointID);
        return patchpointToFunction.get(startPatchpointID).address;
    }

    int[] getPatchpointOffsets(long patchpointID) {
        if (patchpointsByID.containsKey(patchpointID)) {
            return patchpointsByID.get(patchpointID).stream().mapToInt(r -> r.instructionOffset).toArray();
        }
        return new int[0];
    }

    private static final int STATEPOINT_HEADER_LOCATION_COUNT = 3;
    private static final int STATEPOINT_DEOPT_COUNT_LOCATION_INDEX = 2;

    @FunctionalInterface
    public interface StatepointOffsetCallback {
        void accept(int derivedOffset, int baseOffset, boolean compressed);
    }

    void forEachStatepointOffset(long patchpointID, int instructionOffset, StatepointOffsetCallback callback) {
        Set<Record> records = patchpointsByID.get(patchpointID);
        if (records == null) {
            throw shouldNotReachHere("Missing LLVM statepoint stack map record: patchpointID=%s, instructionOffset=%s", patchpointID, instructionOffset);
        }
        Location[] locations = records.stream().filter(r -> r.instructionOffset == instructionOffset)
                        .findFirst().orElseThrow(() -> shouldNotReachHere("Missing LLVM statepoint stack map record: patchpointID=%s, instructionOffset=%s", patchpointID,
                                        instructionOffset)).locations;
        guaranteeValidStatepoint(locations.length >= STATEPOINT_HEADER_LOCATION_COUNT, patchpointID, instructionOffset,
                        "expected at least %s header locations, found %s", STATEPOINT_HEADER_LOCATION_COUNT, locations.length);

        Location deoptCountLocation = locations[STATEPOINT_DEOPT_COUNT_LOCATION_INDEX];
        guaranteeValidStatepoint(deoptCountLocation.type == Location.Type.Constant, patchpointID, instructionOffset,
                        "expected deopt count location to be a constant, found %s", formatLocation(deoptCountLocation));
        int deoptCount = deoptCountLocation.offset;
        guaranteeValidStatepoint(deoptCount >= 0, patchpointID, instructionOffset, "negative deopt count %s", deoptCount);
        guaranteeValidStatepoint(STATEPOINT_HEADER_LOCATION_COUNT + deoptCount <= locations.length, patchpointID, instructionOffset,
                        "deopt count %s exceeds location count %s", deoptCount, locations.length);

        EconomicSet<Integer> compressedOffsets = EconomicSet.create();
        for (int i = STATEPOINT_HEADER_LOCATION_COUNT; i < STATEPOINT_HEADER_LOCATION_COUNT + deoptCount; ++i) {
            Location loc = locations[i];
            guaranteeValidStatepoint(loc.type == Location.Type.Indirect, patchpointID, instructionOffset,
                            "expected compressed addrspace(2) location at index %s to be indirect, found %s", i, formatLocation(loc));
            int[] offsets = getStackOffsets(patchpointID, loc);
            guaranteeValidStatepoint(offsets.length == 1, patchpointID, instructionOffset,
                            "expected compressed addrspace(2) location at index %s to map to one stack slot, found %s slots in %s", i, offsets.length, formatLocation(loc));
            compressedOffsets.add(offsets[0]);
        }

        EconomicSet<Integer> seenOffsets = EconomicSet.create();
        EconomicSet<Integer> seenBases = EconomicSet.create();
        guaranteeValidStatepoint((locations.length - STATEPOINT_HEADER_LOCATION_COUNT - deoptCount) % 2 == 0, patchpointID, instructionOffset,
                        "expected base/reference locations to be paired, found %s locations after the header and compressed addrspace(2) section",
                        locations.length - STATEPOINT_HEADER_LOCATION_COUNT - deoptCount);
        for (int i = STATEPOINT_HEADER_LOCATION_COUNT + deoptCount; i < locations.length; i += 2) {
            Location base = locations[i];
            Location ref = locations[i + 1];

            if (base.type == Location.Type.Constant || ref.type == Location.Type.Constant) {
                guaranteeValidStatepoint(base.type == ref.type && base.offset == ref.offset, patchpointID, instructionOffset,
                                "constant base/reference pair mismatch at indexes %s/%s: base=%s, ref=%s", i, i + 1, formatLocation(base), formatLocation(ref));
                if (base.offset != 0) {
                    /*
                     * We are seeing a hard-coded pointer. This will most probably cause a segfault
                     * at runtime, but we have to emit it either way and not fail during
                     * compilation.
                     */
                    seenBases.add((int) (base.offset - getFunctionOffset(patchpointID)));
                    seenOffsets.add((int) (ref.offset - getFunctionOffset(patchpointID)));
                }
                continue;
            }

            guaranteeValidStatepoint(base.type == Location.Type.Indirect, patchpointID, instructionOffset,
                            "expected base location at index %s to be indirect, found %s", i, formatLocation(base));
            int[] baseOffsets = getStackOffsets(patchpointID, base);

            guaranteeValidStatepoint(ref.type == Location.Type.Indirect, patchpointID, instructionOffset,
                            "expected reference location at index %s to be indirect, found %s", i + 1, formatLocation(ref));
            int[] derivedOffsets = getStackOffsets(patchpointID, ref);

            guaranteeValidStatepoint(baseOffsets.length == derivedOffsets.length, patchpointID, instructionOffset,
                            "base/reference stack slot count mismatch at indexes %s/%s: baseSlots=%s, referenceSlots=%s", i, i + 1, baseOffsets.length, derivedOffsets.length);

            for (int j = 0; j < baseOffsets.length; ++j) {
                int baseOffset = baseOffsets[j];
                int derivedOffset = derivedOffsets[j];

                seenBases.add(baseOffset);
                /*
                 * Derived pointers have their base already registered on the stackmap. Match the
                 * 23.1 backend behavior and keep the first location reported for a stack slot.
                 */
                if (!seenOffsets.contains(derivedOffset)) {
                    seenOffsets.add(derivedOffset);
                    boolean compressedBase = compressedOffsets.contains(baseOffset);
                    boolean compressedDerived = compressedOffsets.contains(derivedOffset);
                    assert compressedDerived == compressedBase : invalidStatepointMessage(patchpointID, instructionOffset,
                                    "compressed addrspace(2) base/reference mismatch: baseOffset=%s, derivedOffset=%s, compressedOffsets=%s",
                                    baseOffset, derivedOffset, formatOffsets(compressedOffsets));
                    callback.accept(derivedOffset, baseOffset, compressedDerived);
                }
            }
        }

        guaranteeValidStatepoint(seenOffsets.containsAll(seenBases), patchpointID, instructionOffset,
                        "not all base offsets are also reported as references: seenBases=%s, seenOffsets=%s", formatOffsets(seenBases), formatOffsets(seenOffsets));
    }

    private static void guaranteeValidStatepoint(boolean condition, long patchpointID, int instructionOffset, String message, Object... args) {
        if (!condition) {
            throw shouldNotReachHere(invalidStatepointMessage(patchpointID, instructionOffset, message, args));
        }
    }

    private static String invalidStatepointMessage(long patchpointID, int instructionOffset, String message, Object... args) {
        return "Invalid LLVM statepoint stack map entry: patchpointID=" + patchpointID + ", instructionOffset=" + instructionOffset + ": " + String.format(message, args);
    }

    private static String formatLocation(Location location) {
        return "Location[type=" + location.type + ", size=" + location.size + ", regNum=" + location.regNum + ", offset=" + location.offset + "]";
    }

    private static String formatOffsets(EconomicSet<Integer> offsets) {
        StringBuilder result = new StringBuilder("[");
        String separator = "";
        for (int offset : offsets) {
            result.append(separator).append(offset);
            separator = ", ";
        }
        return result.append(']').toString();
    }

    private int[] getStackOffsets(long patchpointID, Location location) {
        int wordSize = SubstrateTarget.getWordSize();
        assert location.size % wordSize == 0;
        int numLocations = location.size / wordSize;
        assert numLocations > 0;

        int baseOffset;
        if (location.regNum == LLVMTargetSpecific.get().getStackPointerDwarfRegNum()) {
            baseOffset = location.offset;
        } else if (location.regNum == LLVMTargetSpecific.get().getFramePointerDwarfRegNum()) {
            /*
             * Convert frame-relative offset (negative) to a stack-relative offset (positive).
             */
            baseOffset = location.offset + NumUtil.safeToInt(getFunctionStackSize(patchpointID)) + LLVMTargetSpecific.get().getFramePointerOffset();
        } else {
            throw shouldNotReachHere("found other register " + patchpointID + " " + location.regNum);
        }
        assert baseOffset >= 0 && baseOffset + location.size < getFunctionStackSize(patchpointID);

        int[] offsets = new int[numLocations];
        for (int i = 0; i < numLocations; ++i) {
            offsets[i] = baseOffset + i * wordSize;
        }

        return offsets;
    }
}
