/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package jdk.graal.compiler.loop.test;

import org.junit.Assert;
import org.junit.Test;

import jdk.graal.compiler.loop.phases.SimulationBasedLoopPeeling;
import jdk.graal.compiler.loop.phases.SimulationBasedLoopPolicies;
import jdk.graal.compiler.phases.common.priorityinline.PriorityInliningPhase;

import jdk.graal.compiler.core.test.GraalCompilerTest;
import jdk.graal.compiler.debug.DebugContext;
import jdk.graal.compiler.loop.phases.LoopPeelingPhase;
import jdk.graal.compiler.nodes.LoopBeginNode;
import jdk.graal.compiler.nodes.StructuredGraph;
import jdk.graal.compiler.nodes.loop.Loop;
import jdk.graal.compiler.phases.OptimisticOptimizations;
import jdk.graal.compiler.phases.PhaseSuite;
import jdk.graal.compiler.phases.common.CanonicalizerPhase;
import jdk.graal.compiler.phases.common.DisableOverflownCountedLoopsPhase;
import jdk.graal.compiler.phases.common.util.LoopUtility;
import jdk.graal.compiler.phases.tiers.HighTierContext;
import jdk.vm.ci.meta.ResolvedJavaMethod;

public class SimulationBasedLoopPeelingSwitchTest extends GraalCompilerTest {

    public static int snippet(Object number) {
        if (number == null) {
            return -1;
        }
        /*
         * Models the state-machine loop generated by javac for a guarded pattern switch. The
         * constant state phi feeding the integer switch is the shape recognized by
         * LoopUtility.maybeSwitchWhenLoop.
         */
        int state = 0;
        while (true) {
            switch (state) {
                case 0:
                    if (number instanceof Integer i) {
                        if (i >= 0) {
                            return 0;
                        }
                        state = 1;
                    } else {
                        state = 2;
                    }
                    break;
                case 1:
                    if (number instanceof Integer) {
                        return 1;
                    }
                    state = 2;
                    break;
                case 2:
                    if (number instanceof Long) {
                        return 2;
                    }
                    return -1;
                default:
                    throw new AssertionError(state);
            }
        }
    }

    @Test
    public void testSnippetWhiteBox() throws Throwable {
        ResolvedJavaMethod method = getResolvedJavaMethod("snippet");
        executeExpected(method, null, -1);

        DebugContext debug = getDebugContext(getInitialOptions(), null, null);
        try (DebugContext.Scope _ = debug.scope(getClass(), method, getCodeCache())) {
            StructuredGraph graph = parseEager(method, StructuredGraph.AllowAssumptions.YES);
            PhaseSuite<HighTierContext> graphBuilderSuite = getDefaultGraphBuilderSuite();
            HighTierContext context = new HighTierContext(getProviders(), graphBuilderSuite, OptimisticOptimizations.ALL);

            CanonicalizerPhase canon = createCanonicalizerPhase();
            new PriorityInliningPhase(canon, graph.getOptions()).apply(graph, context);
            new DisableOverflownCountedLoopsPhase().apply(graph);
            Loop loop = context.getLoopsDataProvider().getLoopsData(graph).loops().getFirst();
            loop.detectCounted();
            Assert.assertTrue("state-machine loop must be recognized as a guarded switch loop", LoopUtility.maybeSwitchWhenLoop(loop));
            new LoopPeelingPhase(new SimulationBasedLoopPolicies(SimulationBasedLoopPeeling.getHighTierPeelingFactors(getInitialOptions())), canon).apply(graph, context);
            Assert.assertTrue("simulation-based peeling must peel the recognized loop",
                            graph.getNodes().filter(LoopBeginNode.class).filter(loopBegin -> ((LoopBeginNode) loopBegin).peelings() > 0).isNotEmpty());
        }
    }

    @Test
    public void testSnippet() {
        test("snippet", -1);
    }

}
