/*
 * Copyright (c) 2013, 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
package jdk.graal.compiler.replacements.nodes;

import static jdk.graal.compiler.nodeinfo.InputType.Memory;

import java.util.EnumSet;

import org.graalvm.word.LocationIdentity;

import jdk.graal.compiler.core.common.Stride;
import jdk.graal.compiler.core.common.StrideUtil;
import jdk.graal.compiler.core.common.memory.BarrierType;
import jdk.graal.compiler.core.common.memory.MemoryOrderMode;
import jdk.graal.compiler.core.common.spi.ForeignCallDescriptor;
import jdk.graal.compiler.core.common.type.IntegerStamp;
import jdk.graal.compiler.core.common.type.Stamp;
import jdk.graal.compiler.core.common.type.StampFactory;
import jdk.graal.compiler.debug.GraalError;
import jdk.graal.compiler.graph.NodeClass;
import jdk.graal.compiler.lir.GenerateStub;
import jdk.graal.compiler.nodeinfo.NodeCycles;
import jdk.graal.compiler.nodeinfo.NodeInfo;
import jdk.graal.compiler.nodeinfo.NodeSize;
import jdk.graal.compiler.nodes.ConstantNode;
import jdk.graal.compiler.nodes.FixedWithNextNode;
import jdk.graal.compiler.nodes.FrameState;
import jdk.graal.compiler.nodes.NamedLocationIdentity;
import jdk.graal.compiler.nodes.NodeView;
import jdk.graal.compiler.nodes.StructuredGraph;
import jdk.graal.compiler.nodes.ValueNode;
import jdk.graal.compiler.nodes.calc.AddNode;
import jdk.graal.compiler.nodes.memory.MemoryAnchorNode;
import jdk.graal.compiler.nodes.memory.ReadNode;
import jdk.graal.compiler.nodes.memory.WriteNode;
import jdk.graal.compiler.nodes.memory.address.AddressNode;
import jdk.graal.compiler.nodes.memory.address.OffsetAddressNode;
import jdk.graal.compiler.nodes.spi.Lowerable;
import jdk.graal.compiler.nodes.spi.LoweringTool;
import jdk.graal.compiler.nodes.spi.NodeLIRBuilderTool;
import jdk.graal.compiler.replacements.NodeStrideUtil;
import jdk.graal.compiler.vector.architecture.VectorLoweringProvider;
import jdk.graal.compiler.vector.nodes.simd.SimdStamp;
import jdk.vm.ci.meta.JavaKind;

// JaCoCo Exclude

/**
 * Specialized arraycopy stub that assumes disjoint source and target arrays, and supports
 * compression and inflation depending on {@code strideSrc} and {@code strideDst}, and endian
 * conversion depending on {@code reverseBytes}.
 */
@NodeInfo(allowedUsageTypes = {Memory}, cycles = NodeCycles.CYCLES_UNKNOWN, size = NodeSize.SIZE_128)
public class ArrayCopyWithConversionsNode extends MemoryKillStubIntrinsicNode implements Lowerable {

    public static final NodeClass<ArrayCopyWithConversionsNode> TYPE = NodeClass.create(ArrayCopyWithConversionsNode.class);

    private static final int MAX_CONSTANT_COPY_BYTES = 128;
    private static final int MAX_CONSTANT_COPY_CHUNKS = 8;

    /**
     * TruffleStrings is using the same stub generated by this node to write to {@code byte[]}
     * arrays and native buffers.
     */
    public static final LocationIdentity[] KILLED_LOCATIONS = {NamedLocationIdentity.getArrayLocation(JavaKind.Byte), NamedLocationIdentity.OFF_HEAP_LOCATION};

    private final Stride strideSrc;
    private final Stride strideDst;
    private final boolean reverseBytes;
    @Input protected ValueNode arraySrc;
    @Input protected ValueNode offsetSrc;
    @Input protected ValueNode arrayDst;
    @Input protected ValueNode offsetDst;
    @Input protected ValueNode length;

    /**
     * Optional argument for dispatching to any combination of strides at runtime, as described in
     * {@link StrideUtil}.
     */
    @OptionalInput protected ValueNode dynamicStrides;

    /**
     * Arraycopy operation for arbitrary source and destination arrays, with arbitrary byte offset,
     * with support for arbitrary compression and inflation of {@link JavaKind#Byte 8 bit},
     * {@link JavaKind#Char 16 bit} or {@link JavaKind#Int 32 bit} array elements.
     *
     * @param strideSrc source stride. May be {@link JavaKind#Byte 8 bit}, {@link JavaKind#Char 16
     *            bit} or {@link JavaKind#Int 32 bit}.
     * @param strideDst target stride. May be {@link JavaKind#Byte 8 bit}, {@link JavaKind#Char 16
     *            bit} or {@link JavaKind#Int 32 bit}.
     * @param arraySrc source array.
     * @param offsetSrc offset to be added to arraySrc, in bytes. Must include array base offset!
     * @param arrayDst destination array.
     * @param offsetDst offset to be added to arrayDst, in bytes. Must include array base offset!
     * @param length length of the region to copy, scaled to strideDst.
     */
    public ArrayCopyWithConversionsNode(ValueNode arraySrc, ValueNode offsetSrc, ValueNode arrayDst, ValueNode offsetDst, ValueNode length,
                    @ConstantNodeParameter Stride strideSrc,
                    @ConstantNodeParameter Stride strideDst) {
        this(TYPE, arraySrc, offsetSrc, arrayDst, offsetDst, length, null, strideSrc, strideDst, false, null);
    }

    public ArrayCopyWithConversionsNode(ValueNode arraySrc, ValueNode offsetSrc, ValueNode arrayDst, ValueNode offsetDst, ValueNode length,
                    @ConstantNodeParameter Stride strideSrc,
                    @ConstantNodeParameter Stride strideDst,
                    @ConstantNodeParameter EnumSet<?> runtimeCheckedCPUFeatures) {
        this(TYPE, arraySrc, offsetSrc, arrayDst, offsetDst, length, null, strideSrc, strideDst, false, runtimeCheckedCPUFeatures);
    }

    public ArrayCopyWithConversionsNode(ValueNode arraySrc, ValueNode offsetSrc, ValueNode arrayDst, ValueNode offsetDst, ValueNode length,
                    @ConstantNodeParameter Stride stride,
                    @ConstantNodeParameter boolean reverseBytes) {
        this(TYPE, arraySrc, offsetSrc, arrayDst, offsetDst, length, null, stride, stride, reverseBytes, null);
    }

    public ArrayCopyWithConversionsNode(ValueNode arraySrc, ValueNode offsetSrc, ValueNode arrayDst, ValueNode offsetDst, ValueNode length,
                    @ConstantNodeParameter Stride stride,
                    @ConstantNodeParameter boolean reverseBytes,
                    @ConstantNodeParameter EnumSet<?> runtimeCheckedCPUFeatures) {
        this(TYPE, arraySrc, offsetSrc, arrayDst, offsetDst, length, null, stride, stride, reverseBytes, runtimeCheckedCPUFeatures);
    }

    /**
     * Variant with dynamicStride parameter, as described in {@link StrideUtil}.
     */
    public ArrayCopyWithConversionsNode(ValueNode arraySrc, ValueNode offsetSrc, ValueNode arrayDst, ValueNode offsetDst, ValueNode length,
                    ValueNode dynamicStrides) {
        this(TYPE, arraySrc, offsetSrc, arrayDst, offsetDst, length, dynamicStrides, null, null, false, null);
    }

    public ArrayCopyWithConversionsNode(ValueNode arraySrc, ValueNode offsetSrc, ValueNode arrayDst, ValueNode offsetDst, ValueNode length,
                    ValueNode dynamicStrides,
                    @ConstantNodeParameter EnumSet<?> runtimeCheckedCPUFeatures) {
        this(TYPE, arraySrc, offsetSrc, arrayDst, offsetDst, length, dynamicStrides, null, null, false, runtimeCheckedCPUFeatures);
    }

    protected ArrayCopyWithConversionsNode(NodeClass<? extends ArrayCopyWithConversionsNode> c,
                    ValueNode arraySrc, ValueNode offsetSrc, ValueNode arrayDst, ValueNode offsetDst, ValueNode length, ValueNode dynamicStrides,
                    @ConstantNodeParameter Stride strideSrc,
                    @ConstantNodeParameter Stride strideDst,
                    @ConstantNodeParameter boolean reverseBytes,
                    @ConstantNodeParameter EnumSet<?> runtimeCheckedCPUFeatures) {
        // TruffleStrings is using the same stub generated by this node to read from
        // byte[]/char[]/int[] arrays and native buffers, so we have to use LocationIdentity.any()
        // here.
        super(c, StampFactory.forKind(JavaKind.Void), runtimeCheckedCPUFeatures, LocationIdentity.any());
        this.strideSrc = strideSrc;
        this.strideDst = strideDst;
        this.reverseBytes = reverseBytes;
        this.arraySrc = arraySrc;
        this.offsetSrc = offsetSrc;
        this.arrayDst = arrayDst;
        this.offsetDst = offsetDst;
        this.length = length;
        this.dynamicStrides = dynamicStrides;
    }

    @NodeIntrinsic
    @GenerateStub(name = "arrayCopyWithConversionsS1S1", parameters = {"S1", "S1"})
    @GenerateStub(name = "arrayCopyWithConversionsS1S2", parameters = {"S1", "S2"})
    @GenerateStub(name = "arrayCopyWithConversionsS1S4", parameters = {"S1", "S4"})
    @GenerateStub(name = "arrayCopyWithConversionsS2S1", parameters = {"S2", "S1"})
    @GenerateStub(name = "arrayCopyWithConversionsS2S2", parameters = {"S2", "S2"})
    @GenerateStub(name = "arrayCopyWithConversionsS2S4", parameters = {"S2", "S4"})
    @GenerateStub(name = "arrayCopyWithConversionsS4S1", parameters = {"S4", "S1"})
    @GenerateStub(name = "arrayCopyWithConversionsS4S2", parameters = {"S4", "S2"})
    @GenerateStub(name = "arrayCopyWithConversionsS4S4", parameters = {"S4", "S4"})
    public static native void arrayCopy(Object arraySrc, long offsetSrc, Object arrayDst, long offsetDst, int length,
                    @ConstantNodeParameter Stride strideSrc,
                    @ConstantNodeParameter Stride strideDst);

    @NodeIntrinsic
    public static native void arrayCopy(Object arraySrc, long offsetSrc, Object arrayDst, long offsetDst, int length,
                    @ConstantNodeParameter Stride strideSrc,
                    @ConstantNodeParameter Stride strideDst,
                    @ConstantNodeParameter EnumSet<?> runtimeCheckedCPUFeatures);

    @NodeIntrinsic
    @GenerateStub(name = "arrayCopyWithReverseBytesS2", parameters = {"S2", "true"})
    @GenerateStub(name = "arrayCopyWithReverseBytesS4", parameters = {"S4", "true"})
    public static native void arrayCopyWithReverseBytes(Object arraySrc, long offsetSrc, Object arrayDst, long offsetDst, int length,
                    @ConstantNodeParameter Stride stride,
                    @ConstantNodeParameter boolean reverseBytes);

    @NodeIntrinsic
    public static native void arrayCopyWithReverseBytes(Object arraySrc, long offsetSrc, Object arrayDst, long offsetDst, int length,
                    @ConstantNodeParameter Stride stride,
                    @ConstantNodeParameter boolean reverseBytes,
                    @ConstantNodeParameter EnumSet<?> runtimeCheckedCPUFeatures);

    @NodeIntrinsic
    @GenerateStub(name = "arrayCopyWithConversionsDynamicStrides")
    public static native void arrayCopy(Object arraySrc, long offsetSrc, Object arrayDst, long offsetDst, int length, int stride);

    @NodeIntrinsic
    public static native void arrayCopy(Object arraySrc, long offsetSrc, Object arrayDst, long offsetDst, int length, int stride,
                    @ConstantNodeParameter EnumSet<?> runtimeCheckedCPUFeatures);

    public boolean isReverseBytes() {
        return reverseBytes;
    }

    public Stride getReverseBytesStride() {
        return strideDst;
    }

    public ValueNode getLength() {
        return length;
    }

    @Override
    public void lower(LoweringTool tool) {
        /*
         * This node is a MultiMemoryKill. High-tier lowering verifies memory-kill shape and rejects
         * replacing it with plain single-kill writes. Keep this expansion in low tier, where this
         * check no longer applies.
         */
        if (tool.getLoweringStage() != LoweringTool.StandardLoweringStage.LOW_TIER || !length.isJavaConstant()) {
            return;
        }
        int constantLength = length.asJavaConstant().asInt();
        int maxVectorSizeBytes = maxVectorSizeBytes(tool);
        if (!canLowerConstantLengthCopy(maxVectorSizeBytes, strideSrc, strideDst, reverseBytes, constantLength)) {
            return;
        }

        lowerConstantLengthCopy(constantLength, maxVectorSizeBytes);
    }

    /**
     * Lowers this short constant-length copy to a straight-line sequence of fixed reads followed by
     * fixed writes.
     */
    private void lowerConstantLengthCopy(int constantLength, int maxVectorSizeBytes) {
        int byteLength = constantLength << strideDst.log2;
        int chunkSize = Integer.highestOneBit(Math.min(byteLength, maxVectorSizeBytes));
        FixedWithNextNode last = lowerToReadWriteCopy(this, arraySrc, offsetSrc, arrayDst, offsetDst,
                        chunkOffsets(byteLength, chunkSize), accessStamp(chunkSize), getLocationIdentity(), LocationIdentity.any(), stateAfter());

        /* Preserve a memory checkpoint for usages of the original multi-kill node. */
        StructuredGraph graph = graph();
        MemoryAnchorNode memoryAnchor = graph.add(new MemoryAnchorNode(getKilledLocationIdentities()));
        replaceAtUsages(memoryAnchor, Memory);
        graph.addAfterFixed(last, memoryAnchor);
        graph.removeFixed(this);
    }

    /**
     * Inserts a constant-length copy as fixed reads followed by fixed writes.
     *
     * @return the last inserted write
     */
    static WriteNode lowerToReadWriteCopy(FixedWithNextNode predecessor, ValueNode arraySrc, ValueNode offsetSrc, ValueNode arrayDst, ValueNode offsetDst,
                    int[] chunkOffsets, Stamp accessStamp, LocationIdentity readLocation, LocationIdentity writeLocation, FrameState stateAfter) {
        StructuredGraph graph = predecessor.graph();
        ReadNode[] loads = new ReadNode[chunkOffsets.length];
        WriteNode[] stores = new WriteNode[chunkOffsets.length];
        for (int i = 0; i < chunkOffsets.length; i++) {
            AddressNode srcAddress = createAddress(graph, arraySrc, offsetSrc, chunkOffsets[i]);
            loads[i] = graph.add(new ReadNode(srcAddress, readLocation, accessStamp, BarrierType.NONE, MemoryOrderMode.PLAIN));
        }
        for (int i = 0; i < chunkOffsets.length; i++) {
            AddressNode dstAddress = createAddress(graph, arrayDst, offsetDst, chunkOffsets[i]);
            stores[i] = graph.add(new WriteNode(dstAddress, writeLocation, loads[i], BarrierType.NONE, MemoryOrderMode.PLAIN));
            /* Preserve the frame state from the side-effecting copy node that these writes replace. */
            stores[i].setStateAfter(stateAfter);
        }

        graph.addAfterFixed(predecessor, loads[0]);
        FixedWithNextNode last = loads[0];
        for (int i = 1; i < loads.length; i++) {
            graph.addAfterFixed(last, loads[i]);
            last = loads[i];
        }
        for (WriteNode store : stores) {
            graph.addAfterFixed(last, store);
            last = store;
        }
        return stores[stores.length - 1];
    }

    /**
     * Returns true if a copy can be expanded to a small straight-line fixed-node sequence instead
     * of a stub call. This lowering is restricted to non-reversing copies with one statically known
     * stride used by both source and destination, a positive constant byte length, and a bounded
     * number of chunks.
     */
    public static boolean canLowerConstantLengthCopy(int maxVectorSizeBytes, Stride strideSrc, Stride strideDst, boolean reverseBytes, int constantLength) {
        if (reverseBytes || constantLength < 0 || strideSrc == null || strideSrc != strideDst) {
            return false;
        }
        long byteLengthLong = (long) constantLength << strideSrc.log2;
        if (byteLengthLong <= 0 || byteLengthLong > MAX_CONSTANT_COPY_BYTES) {
            return false;
        }
        int byteLength = (int) byteLengthLong;
        int chunkSize = Integer.highestOneBit(Math.min(byteLength, maxVectorSizeBytes));
        return chunkSize != 0 && chunkCount(byteLength, chunkSize) <= MAX_CONSTANT_COPY_CHUNKS;
    }

    static int maxVectorSizeBytes(LoweringTool tool) {
        if (tool.getLowerer() instanceof VectorLoweringProvider vectorLoweringProvider) {
            return vectorLoweringProvider.getVectorArchitecture().getMaxVectorLength(IntegerStamp.create(Byte.SIZE));
        }
        return Long.BYTES;
    }

    private static int chunkCount(int byteLength, int chunkSize) {
        return (byteLength + chunkSize - 1) / chunkSize;
    }

    /**
     * Returns the byte offsets used to cover a constant-length copy with fixed-size chunks. Every
     * returned offset starts a {@code chunkSize}-byte access that is fully contained in the copied
     * byte range. If {@code byteLength} is not a multiple of {@code chunkSize}, the final chunk is
     * shifted back to end exactly at {@code byteLength}; this may overlap the previous chunk, but it
     * still covers the tail without introducing a smaller access kind.
     */
    static int[] chunkOffsets(int byteLength, int chunkSize) {
        int chunkCount = chunkCount(byteLength, chunkSize);
        int[] chunkOffsets = new int[chunkCount];
        for (int i = 0; i < chunkOffsets.length; i++) {
            chunkOffsets[i] = Math.min(i * chunkSize, byteLength - chunkSize);
        }
        return chunkOffsets;
    }

    static Stamp accessStamp(int chunkSize) {
        return switch (chunkSize) {
            case 1 -> StampFactory.forKind(JavaKind.Byte);
            case 2 -> StampFactory.forKind(JavaKind.Short);
            case 4 -> StampFactory.forKind(JavaKind.Int);
            case 8 -> StampFactory.forKind(JavaKind.Long);
            case 16, 32, 64 -> SimdStamp.broadcast(IntegerStamp.create(Byte.SIZE), chunkSize);
            default -> throw GraalError.shouldNotReachHereUnexpectedValue(chunkSize);
        };
    }

    static AddressNode createAddress(StructuredGraph graph, ValueNode base, ValueNode offset, int byteOffset) {
        ValueNode finalOffset = offset;
        if (byteOffset != 0) {
            ConstantNode offsetConstant = ConstantNode.forIntegerStamp(offset.stamp(NodeView.DEFAULT), byteOffset, graph);
            finalOffset = graph.addOrUniqueWithInputs(AddNode.create(offset, offsetConstant, NodeView.DEFAULT));
        }
        return graph.unique(new OffsetAddressNode(base, finalOffset));
    }

    public int getDirectStubCallIndex() {
        return NodeStrideUtil.getDirectStubCallIndex(dynamicStrides, strideSrc, strideDst);
    }

    @Override
    public ForeignCallDescriptor getForeignCallDescriptor() {
        return ArrayCopyWithConversionsForeignCalls.getStub(this);
    }

    @Override
    public ValueNode[] getForeignCallArguments() {
        if (getDirectStubCallIndex() < 0) {
            return new ValueNode[]{arraySrc, offsetSrc, arrayDst, offsetDst, length, dynamicStrides};
        } else {
            return new ValueNode[]{arraySrc, offsetSrc, arrayDst, offsetDst, length};
        }
    }

    @Override
    public void emitIntrinsic(NodeLIRBuilderTool gen) {
        if (reverseBytes) {
            gen.getLIRGeneratorTool().emitArrayCopyWithReverseBytes(
                            strideDst,
                            getRuntimeCheckedCPUFeatures(),
                            gen.operand(arraySrc),
                            gen.operand(offsetSrc),
                            gen.operand(arrayDst),
                            gen.operand(offsetDst),
                            gen.operand(length));
        } else if (getDirectStubCallIndex() < 0) {
            gen.getLIRGeneratorTool().emitArrayCopyWithConversion(
                            getRuntimeCheckedCPUFeatures(),
                            gen.operand(arraySrc),
                            gen.operand(offsetSrc),
                            gen.operand(arrayDst),
                            gen.operand(offsetDst),
                            gen.operand(length),
                            gen.operand(dynamicStrides));
        } else {
            gen.getLIRGeneratorTool().emitArrayCopyWithConversion(
                            NodeStrideUtil.getConstantStrideA(dynamicStrides, strideSrc),
                            NodeStrideUtil.getConstantStrideB(dynamicStrides, strideDst),
                            getRuntimeCheckedCPUFeatures(),
                            gen.operand(arraySrc),
                            gen.operand(offsetSrc),
                            gen.operand(arrayDst),
                            gen.operand(offsetDst),
                            gen.operand(length));
        }
    }

    /**
     * TruffleStrings is using the same stub generated by this node to write to {@code byte[]}
     * arrays and native buffers.
     */
    @Override
    public LocationIdentity[] getKilledLocationIdentities() {
        return KILLED_LOCATIONS;
    }
}
