#
# Copyright (c) 2018, 2019, Oracle and/or its affiliates.
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are
# permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of
# conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of
# conditions and the following disclaimer in the documentation and/or other materials provided
# with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to
# endorse or promote products derived from this software without specific prior written
# permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
# GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
# AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.
#
QUIETLY$(MX_VERBOSE)  = @

.PHONY: default

default: tool-info.txt

ifdef CLANG_CC
  CLANG=$(CLANG_CC)
else
  CLANG?=clang
endif
ifdef CLANG_CXX
  CLANGXX=$(CLANG_CXX)
else
  CLANGXX?=clang++
endif
ifdef CLANG_LLVM_AS
  LLVM_AS=$(CLANG_LLVM_AS)
else
  LLVM_AS?=llvm-as
endif
ifdef CLANG_LLVM_DIS
  LLVM_DIS=$(CLANG_LLVM_DIS)
else
  LLVM_DIS?=llvm-dis
endif
ifdef CLANG_LLVM_OPT
  LLVM_OPT=$(CLANG_LLVM_OPT)
  OPT=$(CLANG_LLVM_OPT)
else
  LLVM_OPT?=opt
  OPT=$(LLVM_OPT)
endif
ifdef CLANG_LLVM_OBJCOPY
  LLVM_OBJCOPY=$(CLANG_LLVM_OBJCOPY)
else
  LLVM_OBJCOPY?=llvm-objcopy
endif
FC?=gfortran

CFLAGS+= $(SUITE_CFLAGS)
CXXFLAGS+= $(SUITE_CXXFLAGS) -std=c++11 -stdlib=libc++
CPPFLAGS+= $(SUITE_CPPFLAGS)
LDFLAGS+= $(SUITE_LDFLAGS)

ifndef NO_FEMBED_BITCODE
BC_FILE=
EMBED_BC=-fembed-bitcode
else # NO_FEMBED_BITCODE it set
ifeq ($(OS), darwin)
BC_FILE=
EMBED_BC=-fembed-bitcode
else # not darwin
EMBED_BC=
BC_FILE=%/O0.bc.o
%.bc.o: %.bc
	$(QUIETLY) $(LLVM_OBJCOPY) -I binary -O elf64-x86-64 -B i386:x86-64 --rename-section .data=.llvmbc $< $@
endif # darwin
endif # NO_FEMBED_BITCODE

ifdef CLANG_NO_OPTNONE
SULONG_MAKE_CLANG_IMPLICIT_ARGS=
else
SULONG_MAKE_CLANG_IMPLICIT_ARGS=-Xclang -disable-O0-optnone
endif

ifeq ($(OS), darwin)
CLANG_PREFIX=/usr/bin/xcrun --sdk macosx
CLANG:=$(CLANG_PREFIX) $(CLANG)
CLANGXX:=$(CLANG_PREFIX) $(CLANGXX)
else
CLANG_PREFIX=
endif

tool-info.txt:
	@echo "Tools:" > $@
	@echo "  CLANG: $(CLANG)" >> $@
	@echo "  CLANGXX: $(CLANGXX)" >> $@
	@echo "  LLVM_AS: $(LLVM_AS)" >> $@
	@echo "  LLVM_DIS: $(LLVM_DIS)" >> $@
	@echo "  LLVM_OPT: $(LLVM_OPT)" >> $@
	@echo "  LLVM_OBJCOPY: $(LLVM_OBJCOPY)" >> $@
	@echo "  FC: $(FC)" >> $@
	@echo "LLVM_AS Version info:" >> $@
	$(LLVM_AS) --version >> $@
	@cat $@

ifdef GRAALVM_LLVM_HOME
%.cpp.dir/ref.out: LDFLAGS+=-Wl,-rpath,${GRAALVM_LLVM_HOME}/native/lib
%.cc.dir/ref.out: LDFLAGS+=-Wl,-rpath,${GRAALVM_LLVM_HOME}/native/lib
%.C.dir/ref.out: LDFLAGS+=-Wl,-rpath,${GRAALVM_LLVM_HOME}/native/lib
endif

%.c.dir/ref.out: %.c $(BC_FILE)
	@mkdir -p $(shell dirname $@)
	$(QUIETLY) $(CLANG) $(EMBED_BC) -Wno-everything $(CPPFLAGS) $(CFLAGS) $(LDFLAGS) -o $@ $^

%.cpp.dir/ref.out: %.cpp $(BC_FILE)
	@mkdir -p $(shell dirname $@)
	$(QUIETLY) $(CLANGXX) $(EMBED_BC) -Wno-everything $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -o $@ $^

%.cc.dir/ref.out: %.cc $(BC_FILE)
	@mkdir -p $(shell dirname $@)
	$(QUIETLY) $(CLANGXX) $(EMBED_BC) -Wno-everything $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -o $@ $^

%.C.dir/ref.out: %.C $(BC_FILE)
	@mkdir -p $(shell dirname $@)
	$(QUIETLY) $(CLANGXX) $(EMBED_BC) -Wno-everything $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -o $@ $^

%.f.dir/ref.out: %.f $(BC_FILE)
	@mkdir -p $(shell dirname $@)
	$(QUIETLY) $(FC) -w -J$(shell dirname $@) $(CPPFLAGS) $(FFLAGS) $(LDFLAGS) -o $@ $^

%.f90.dir/ref.out: %.f90 $(BC_FILE)
	@mkdir -p $(shell dirname $@)
	$(QUIETLY) $(FC) -w -J$(shell dirname $@) $(CPPFLAGS) $(FFLAGS) $(LDFLAGS) -o $@ $^

%.f03.dir/ref.out: %.f03 $(BC_FILE)
	@mkdir -p $(shell dirname $@)
	$(QUIETLY) $(FC) -w -J$(shell dirname $@) $(CPPFLAGS) $(FFLAGS) $(LDFLAGS) -o $@ $^

%.bc: %.dragonegg.ll
	$(QUIETLY) $(DRAGONEGG_LLVMAS) -o $@ $<

define OPT_RULES
%.c.dir/$(1).bc: %.c
	@mkdir -p $$(shell dirname $$@)
	$(QUIETLY) $(CLANG) -c -emit-llvm $(2) -Wno-everything $(CPPFLAGS) $(CFLAGS) -g -o $$@ $$<

%.cpp.dir/$(1).bc: %.cpp
	@mkdir -p $$(shell dirname $$@)
	$(QUIETLY) $(CLANGXX) -c -emit-llvm $(2) -Wno-everything $(CPPFLAGS) $(CXXFLAGS) -g -o $$@ $$<

%.cc.dir/$(1).bc: %.cc
	@mkdir -p $$(shell dirname $$@)
	$(QUIETLY) $(CLANGXX) -c -emit-llvm $(2) -Wno-everything $(CPPFLAGS) $(CXXFLAGS) -g -o $$@ $$<

%.C.dir/$(1).bc: %.C
	@mkdir -p $$(shell dirname $$@)
	$(QUIETLY) $(CLANGXX) -c -emit-llvm $(2) -Wno-everything $(CPPFLAGS) $(CXXFLAGS) -g -o $$@ $$<

%.f.dir/$(1).dragonegg.ll: %.f
	@mkdir -p $$(shell dirname $$@)
	$(QUIETLY) $(DRAGONEGG_FC) -w -S -fplugin=$(DRAGONEGG) -fplugin-arg-dragonegg-emit-ir -$(1) -J$$(shell dirname $$@) $(CPPFLAGS) $(FFLAGS) -o $$@ $$<

%.f90.dir/$(1).dragonegg.ll: %.f90
	@mkdir -p $$(shell dirname $$@)
	$(QUIETLY) $(DRAGONEGG_FC) -w -S -fplugin=$(DRAGONEGG) -fplugin-arg-dragonegg-emit-ir -$(1) -J$$(shell dirname $$@) $(CPPFLAGS) $(FFLAGS) -o $$@ $$<

%.f03.dir/$(1).dragonegg.ll: %.f03
	@mkdir -p $$(shell dirname $$@)
	$(QUIETLY) $(DRAGONEGG_FC) -w -S -fplugin=$(DRAGONEGG) -fplugin-arg-dragonegg-emit-ir -$(1) -J$$(shell dirname $$@) $(CPPFLAGS) $(FFLAGS) -o $$@ $$<

%.c.dir/gcc_$(1).ll: %.c
	@mkdir -p $$(shell dirname $$@)
	$(QUIETLY) $(DRAGONEGG_GCC) -w -S --std=gnu99 -fplugin=$(DRAGONEGG) -fplugin-arg-dragonegg-emit-ir -$(1) $(CPPFLAGS) $(CFLAGS) -o $$@ $$<

%.ll.dir/$(1).bc: %.ll
	@mkdir -p $$(shell dirname $$@)
	$(QUIETLY) $(LLVM_AS) -o $$@ $$<

endef

$(eval $(call OPT_RULES,O0,-O0 ${SULONG_MAKE_CLANG_IMPLICIT_ARGS}))
$(eval $(call OPT_RULES,O1,-O1))
$(eval $(call OPT_RULES,O2,-O2))
$(eval $(call OPT_RULES,O3,-O3))
