/*
 * Copyright (c) 2026, 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

//JAVA 17+
//DEPS com.fasterxml.jackson.core:jackson-databind:2.22.0
//SOURCES IdeReportReader.java

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.util.Arrays;
import java.util.Base64;
import java.util.HexFormat;

/** Run with {@code jbang IdeReportReaderTest.java}. */
public final class IdeReportReaderTest {
    /* Generated by ide_report.envelope.encode; the hashes below freeze the exact bytes. */
    private static final String UNCOMPRESSED_VECTOR =
                    "U1ZNX0lERV9SRVBPUlQAAQANdGVzdC1wcm9kdWNlcgABAAEAAAAAAAAAAJIAAAAAAAAAkgElNEShTBCIO4CeV4Z5" +
                                    "z4kxF2Xrv4f+0i3fEVmL5hDqA3siZXh0ZW5zaW9ucyI6e30sInBheWxvYWRfc2NvcGUiOiJmdWxsIiwicmVj" +
                                    "b3JkcyI6W3siY2F0ZWdvcnkiOiJyZWZsZWN0aW9uIiwia2luZCI6IkxJTkUiLCJtc2ciOiJyZXNvbHZlZCJ9" +
                                    "XSwic2NoZW1hX3ZlcnNpb24iOjEsInVzZWRfbWV0aG9kcyI6W119";
    private static final String COMPRESSED_VECTOR =
                    "U1ZNX0lERV9SRVBPUlQAAQANdGVzdC1wcm9kdWNlcgABAAEBAAAAAAAAFBIAAAAAAAAAnQGM9Atdzpp1cP3E1oXt9LX0aXue9j6d" +
                                    "ytj/QWJmCe11kh+LCAAAAAAAAv/t2D0OwjAMBeC7eM7Cmp0BCXEBVEVR4v6I/FRJiqiq3L2GO7C9b3v28wV8EH8ap7rkVEkf" +
                                    "XdFq95CtN9XllUnTuIVAigq7XLx0ngc523jKZZdt4TGwa3IundeSvMzut8dVUqyTBAsAAAAAAAAAAAB/R31QVN3M0Zo3l+/Dj" +
                                    "/RF0VbZm8htzr/n3tBP0MxBoxIUAAA=";

    private int passed;

    public static void main(String[] args) throws Exception {
        new IdeReportReaderTest().run();
    }

    private void run() throws Exception {
        test("uncompressed cross-language vector", this::uncompressedVector);
        test("compressed cross-language vector", this::compressedVector);
        test("corruption and truncation", this::corruptionAndTruncation);
        test("decoded payload limit", this::decodedPayloadLimit);
        test("canonical schema validation", this::canonicalSchemaValidation);
        test("command line summary and query", this::commandLine);
        System.out.println("IdeReportReader tests passed: " + passed);
    }

    private void uncompressedVector() throws Exception {
        byte[] bytes = decode(UNCOMPRESSED_VECTOR);
        assertEquals("fdf38a274af2854df206daaf6a22bd80ad843a54e685d125a4a47a9e600d3f68", sha256(bytes));
        var envelope = IdeReportReader.decodeEnvelope(ByteBuffer.wrap(bytes), 1024);
        assertEquals("test-producer", envelope.producerVersion());
        assertEquals("none", envelope.compressionName());

        var report = IdeReportReader.parsePayload(ByteBuffer.wrap(envelope.payload()));
        assertEquals(1, report.schemaVersion());
        assertEquals("full", report.payloadScope());
        assertEquals(1, report.records().size());
        assertEquals("resolved", report.records().get(0).path("msg").textValue());
        assertEquals(0, report.usedMethods().size());
    }

    private void compressedVector() throws Exception {
        byte[] bytes = decode(COMPRESSED_VECTOR);
        assertEquals("4d9e7c2864ee1973f2cd22fc9d63808d5a5588989b324613d0208b99f41261ec", sha256(bytes));
        var envelope = IdeReportReader.decodeEnvelope(bytes, 8192);
        assertEquals("gzip", envelope.compressionName());
        assertEquals(5138, envelope.payload().length);
        assertEquals(1, IdeReportReader.parsePayload(envelope.payload()).records().size());
    }

    private void corruptionAndTruncation() {
        byte[] bytes = decode(UNCOMPRESSED_VECTOR);
        byte[] corrupted = bytes.clone();
        corrupted[corrupted.length - 1] ^= 1;
        expectFailure("checksum mismatch", () -> IdeReportReader.decodeEnvelope(corrupted, 1024));
        expectFailure("payload size does not match", () ->
            IdeReportReader.decodeEnvelope(Arrays.copyOf(bytes, bytes.length - 1), 1024));
        expectFailure("magic", () -> IdeReportReader.decodeEnvelope(new byte[64], 1024));
    }

    private void decodedPayloadLimit() {
        expectFailure("exceeds", () -> IdeReportReader.decodeEnvelope(decode(COMPRESSED_VECTOR), 4096));

        byte[] forged = decode(UNCOMPRESSED_VECTOR);
        int uncompressedSizeOffset = 14 + 4 + "test-producer".length() + 2 + 2 + 1;
        ByteBuffer.wrap(forged).order(ByteOrder.BIG_ENDIAN).putLong(uncompressedSizeOffset, 10_000);
        expectFailure("exceeds", () -> IdeReportReader.decodeEnvelope(forged, 1024));
    }

    private void canonicalSchemaValidation() {
        expectFailure("schema version", () -> parse("""
                        {"schema_version":2,"payload_scope":"full","records":[],"used_methods":[],"extensions":{}}
                        """));
        expectFailure("must be an array", () -> parse("""
                        {"schema_version":1,"payload_scope":"full","records":{},"used_methods":[],"extensions":{}}
                        """));
        expectFailure("Duplicate field", () -> parse("""
                        {"schema_version":1,"schema_version":1,"payload_scope":"full","records":[],"used_methods":[],"extensions":{}}
                        """));
        expectFailure("Trailing token", () -> parse("""
                        {"schema_version":1,"payload_scope":"full","records":[],"used_methods":[],"extensions":{}} {}
                        """));
        expectFailure("must contain only objects", () -> parse("""
                        {"schema_version":1,"payload_scope":"full","records":[1],"used_methods":[],"extensions":{}}
                        """));
    }

    private void commandLine() throws Exception {
        Path path = Files.createTempFile("ide-report-reader", ".ide-report");
        Path jsonPath = Files.createTempFile("ide-report-reader", ".json");
        try {
            Files.write(path, decode(UNCOMPRESSED_VECTOR));
            Files.write(jsonPath, IdeReportReader.decodeEnvelope(decode(UNCOMPRESSED_VECTOR), 1024).payload());
            Invocation summary = invoke(path.toString());
            assertEquals(0, summary.status);
            assertContains(summary.output, "source_format: split");
            assertContains(summary.output, "records: 1");
            assertContains(summary.output, "reflection: 1");

            Invocation query = invoke("--list", "--category", "reflection", path.toString());
            assertEquals(0, query.status);
            assertContains(query.output, "\"msg\" : \"resolved\"");

            Invocation noMatch = invoke("--list", "--kind", "METHOD", path.toString());
            assertEquals(0, noMatch.status);
            assertContains(noMatch.output, "[ ]");

            Invocation jsonSummary = invoke(jsonPath.toString());
            assertEquals(0, jsonSummary.status);
            assertContains(jsonSummary.output, "source_format: json");

            Invocation usage = invoke();
            assertEquals(2, usage.status);
            assertContains(usage.error, "Missing report path");
        } finally {
            Files.deleteIfExists(path);
            Files.deleteIfExists(jsonPath);
        }
    }

    private static void parse(String value) {
        IdeReportReader.parsePayload(value.getBytes(StandardCharsets.UTF_8));
    }

    private static Invocation invoke(String... args) throws Exception {
        try (ByteArrayOutputStream output = new ByteArrayOutputStream();
                        ByteArrayOutputStream error = new ByteArrayOutputStream();
                        PrintStream out = new PrintStream(output, true, StandardCharsets.UTF_8);
                        PrintStream err = new PrintStream(error, true, StandardCharsets.UTF_8)) {
            int status = IdeReportReader.run(args, out, err);
            return new Invocation(status, output.toString(StandardCharsets.UTF_8), error.toString(StandardCharsets.UTF_8));
        }
    }

    private void test(String name, CheckedRunnable test) throws Exception {
        try {
            test.run();
            passed++;
        } catch (Throwable failure) {
            throw new AssertionError("Test failed: " + name, failure);
        }
    }

    private static void expectFailure(String message, CheckedRunnable action) {
        try {
            action.run();
        } catch (IllegalArgumentException expected) {
            assertContains(expected.getMessage(), message);
            return;
        } catch (Exception unexpected) {
            throw new AssertionError("Unexpected exception", unexpected);
        }
        throw new AssertionError("Expected failure containing: " + message);
    }

    private static byte[] decode(String base64) {
        return Base64.getDecoder().decode(base64);
    }

    private static String sha256(byte[] bytes) throws Exception {
        return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));
    }

    private static void assertEquals(Object expected, Object actual) {
        if (!expected.equals(actual)) {
            throw new AssertionError("Expected " + expected + " but was " + actual);
        }
    }

    private static void assertContains(String value, String expected) {
        if (value == null || !value.contains(expected)) {
            throw new AssertionError("Expected '" + value + "' to contain '" + expected + "'");
        }
    }

    @FunctionalInterface
    private interface CheckedRunnable {
        void run() throws Exception;
    }

    private record Invocation(int status, String output, String error) {
    }
}
