# Initialize shaded ICU4J classes at image build time. ICU4J source patches avoid
# snapshotting selected build-time resource caches and parsed resource data.
Args=--initialize-at-build-time=org.graalvm.shadowed.com.ibm.icu \
--features=org.graalvm.shadowed.com.ibm.icu.ICU4JFeature
