/*
 * Copyright (c) 2016, 2016, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
package com.oracle.truffle.regex.tregex.nfa;

import com.oracle.truffle.api.CompilerDirectives;
import com.oracle.truffle.regex.tregex.automaton.IndexedState;
import com.oracle.truffle.regex.tregex.parser.ast.RegexASTNode;
import com.oracle.truffle.regex.tregex.util.DebugUtil;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Represents a single state in the NFA form of a regular expression. States may either be matcher
 * states or final states, where a matcher state matches a set of characters and a final state
 * indicates that a match has been found. A state may represent multiple nodes of a regex AST, if it
 * is the result of a product automaton composition of the "regular" regular expression and its
 * lookaround assertions, e.g. the NFA of an expression like /(?=[ab])a/ will contain a state that
 * matches both the 'a' in the lookahead assertion as well as following 'a' in the expression, and
 * therefore will have a state set containing two AST nodes.
 */
public abstract class NFAState implements IndexedState {

    private final short id;
    private final ASTNodeSet<? extends RegexASTNode> stateSet;
    private boolean hasPrefixStates;
    private List<NFAStateTransition> next;
    private List<NFAStateTransition> prev;
    private List<Integer> possibleResults;

    protected NFAState(short id, ASTNodeSet<? extends RegexASTNode> stateSet, List<NFAStateTransition> next, List<NFAStateTransition> prev, List<Integer> possibleResults) {
        this.id = id;
        this.stateSet = stateSet;
        this.next = next;
        this.prev = prev;
        this.possibleResults = possibleResults;
    }

    protected NFAState(short id, ASTNodeSet<? extends RegexASTNode> stateSet) {
        this(id, stateSet, new ArrayList<>(), new ArrayList<>(), null);
    }

    public ASTNodeSet<? extends RegexASTNode> getStateSet() {
        return stateSet;
    }

    public boolean hasPrefixStates() {
        return hasPrefixStates;
    }

    public void setHasPrefixStates(boolean hasPrefixStates) {
        this.hasPrefixStates = hasPrefixStates;
    }

    /**
     * List of possible next states, sorted by priority.
     */
    public List<NFAStateTransition> getNext() {
        return next;
    }

    public void addLoopBackNext(NFAStateTransition transition) {
        // loopBack transitions always have minimal priority, so no sorting is necessary
        next.add(transition);
    }

    public void setNext(ArrayList<NFAStateTransition> transitions, boolean createReverseTransitions) {
        this.next = transitions;
        if (createReverseTransitions) {
            for (NFAStateTransition t : transitions) {
                t.getTarget().prev.add(t);
            }
        }
    }

    public void removeNext(NFAState state) {
        next.removeIf(x -> x.getTarget() == state);
    }

    /**
     * List of possible previous states, unsorted.
     */
    public List<NFAStateTransition> getPrev() {
        return prev;
    }

    public void addPrev(NFAStateTransition transition) {
        prev.add(transition);
        transition.getSource().next.add(transition);
    }

    @Override
    public short getId() {
        return id;
    }

    /**
     * Set of possible pre-calculated result indices as generated by the
     * {@link NFATraceFinderGenerator}. This set must be sorted, since the index values indicate the
     * priority of their respective pre-calculated results. Example: /(a)|([ab])/ will yield two
     * possible results, where the one corresponding to capture group 1 will have the higher
     * priority, so when a single 'a' is encountered when searching for a match, the pre-calculated
     * result corresponding to capture group 1 must be preferred.
     */
    public List<Integer> getPossibleResults() {
        if (possibleResults == null) {
            return Collections.emptyList();
        }
        return possibleResults;
    }

    public boolean hasPossibleResults() {
        return !(possibleResults == null || possibleResults.isEmpty());
    }

    public void addPossibleResult(int index) {
        if (possibleResults == null) {
            possibleResults = new ArrayList<>();
        }
        int searchResult = Collections.binarySearch(possibleResults, index);
        if (searchResult < 0) {
            possibleResults.add((searchResult + 1) * -1, index);
        }
    }

    @CompilerDirectives.TruffleBoundary
    public String idToString() {
        return getStateSet().stream().map(x -> String.valueOf(x.getId())).collect(Collectors.joining(",", "(", ")")) + "[" + id + "]";
    }

    @Override
    public String toString() {
        return idToString();
    }

    @CompilerDirectives.TruffleBoundary
    public DebugUtil.Table toTable() {
        return toTable("NFAState");
    }

    @CompilerDirectives.TruffleBoundary
    public DebugUtil.Table toTable(String name) {
        DebugUtil.Table table = new DebugUtil.Table("next");
        for (NFAStateTransition transition : next) {
            table.append(transition.toTable());
        }
        return new DebugUtil.Table(name,
                        new DebugUtil.Value("id", id),
                        new DebugUtil.Value("stateSet", idToString()),
                        table);
    }
}
