[properties]
overwrite_parent = true

[[rule]]
files = "*"
any = [
    "christian.humer@oracle.com",
    "jakub.chaloupka@oracle.com",
    "tomas.zezula@oracle.com",
    "boris.spasojevic@oracle.com",
    "matt.dsouza@oracle.com",
]

[[rule]]
files = "*"
any = [
    "doug.simon@oracle.com",
    "tom.rodriguez@oracle.com",
    "david.leopoldseder@oracle.com",
    "gergo.barany@oracle.com",
    "yudi.zheng@oracle.com",
    "raphael.m.mosaner@oracle.com",
]
