package jdk.graal.compiler.lir.alloc.verifier;

import jdk.graal.compiler.core.common.cfg.BasicBlock;
import jdk.graal.compiler.core.common.cfg.BlockMap;
import jdk.graal.compiler.debug.GraalError;
import jdk.graal.compiler.lir.ConstantValue;
import jdk.graal.compiler.lir.LIR;
import jdk.graal.compiler.lir.LIRInstruction;
import jdk.graal.compiler.lir.LIRValueUtil;
import jdk.graal.compiler.lir.StandardOp;
import jdk.graal.compiler.lir.ValueProcedure;
import jdk.graal.compiler.lir.Variable;
import jdk.graal.compiler.lir.VirtualStackSlot;
import jdk.graal.compiler.lir.gen.LIRGenerationResult;
import jdk.graal.compiler.lir.gen.LIRGenerator;
import jdk.graal.compiler.lir.phases.AllocationPhase;
import jdk.graal.compiler.options.EnumOptionKey;
import jdk.graal.compiler.options.Option;
import jdk.graal.compiler.options.OptionKey;
import jdk.graal.compiler.options.OptionType;
import jdk.graal.compiler.options.OptionValues;
import jdk.vm.ci.code.RegisterValue;
import jdk.vm.ci.code.StackSlot;
import jdk.vm.ci.code.TargetDescription;
import jdk.vm.ci.meta.Value;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class RegisterAllocationVerifierPhase extends AllocationPhase {
    public static class Options {
        @Option(help = "Verify that register allocation is indeed, correct", type = OptionType.Debug)
        public static final OptionKey<Boolean> EnableRAVerifier = new OptionKey<>(false);

        @Option(help = "Select which way you want to resolve phi arguments.", type = OptionType.Debug)
        public static final EnumOptionKey<PhiResolution> RAPhiResolution = new EnumOptionKey<>(PhiResolution.FromUsage);

        @Option(help = "Should constants be moved to variables when needed", type = OptionType.Debug)
        public static final OptionKey<Boolean> MoveConstants = new OptionKey<>(true);
    }

    public static String[] ignoredTestCases = {
            // Disable Truffle Related Tests
            // New instructions being added makes the verifier not work, investigate why prealloc is not run.
            "truffle",
            "Truffle",
            "polyglot",
            "Polyglot",
            "Root[]",
            "InstrumentationTestLanguage",
            "NFITest",
            "intCaller1",
            "callee"
    };

    public static boolean isIgnored(String compUnitName) {
        for (String ignoredTest : ignoredTestCases) {
            if (compUnitName.contains(ignoredTest)) {
                return true;
            }
        }
        return false;
    }

    private PhiResolution phiResolution;
    private boolean moveConstants;

    public RegisterAllocationVerifierPhase(OptionValues options) {
        this.phiResolution = Options.RAPhiResolution.getValue(options);
        this.moveConstants = Options.MoveConstants.getValue(options);
    }

    protected PreRegisterAllocationPhase preallocPhaseRAVerifier;
    // protected RAVerifierPreAllocPhase preallocPhaseRAVerifier;

    public AllocationPhase getPreAllocPhase() {
        this.preallocPhaseRAVerifier = new PreRegisterAllocationPhase(phiResolution, moveConstants);
        return this.preallocPhaseRAVerifier;
    }

    @Override
    protected void run(TargetDescription target, LIRGenerationResult lirGenRes, AllocationContext context) {
        var compUnitName = lirGenRes.getCompilationUnitName();
        // if (!compUnitName.contains("nestedSum")) {
        //     return;
        // }

        if (RegisterAllocationVerifierPhase.isIgnored(compUnitName)) {
            // Skipping truffle test cases because they cause trouble with
            // prealloc and getVerifierInstructions, because blocks and
            // instructions that aren't made only by the RA are added.
            return;
        }

        assert this.preallocPhaseRAVerifier != null : "Phase before register allocation was not run, cannot verify it.";

        // var instructions = this.getVerifierInstructions(lirGenRes.getLIR());
        var instructions = this.preallocPhaseRAVerifier.getVerifierInstructions(lirGenRes.getLIR());
        var verifier = new RegisterAllocationVerifier(lirGenRes.getLIR(), instructions, this.phiResolution);
        if (!verifier.run()) {
            // TODO: every error generated by the verifier needs to be a lot more verbose.
            // throw new IllegalStateException("Could not verify the register allocation...");
            // Exception handler

            System.err.println("Verification failed - " + compUnitName);
        }
    }
}
