/*
 * Copyright (c) 2016, Oracle and/or its affiliates.
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of
 * conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of
 * conditions and the following disclaimer in the documentation and/or other materials provided
 * with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors may be used to
 * endorse or promote products derived from this software without specific prior written
 * permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// The content of this file is automatically generated. DO NOT EDIT.

package com.oracle.truffle.llvm.asm.amd64;

import java.io.ByteArrayInputStream;

import com.oracle.truffle.llvm.nodes.base.LLVMExpressionNode;
import com.oracle.truffle.llvm.nodes.impl.func.LLVMInlineAssemblyRootNode;
import com.oracle.truffle.llvm.parser.LLVMBaseType;

// Checkstyle: stop
// @formatter:off
public class Parser {
	public static final int _EOF = 0;
	public static final int _ident = 1;
	public static final int _number = 2;
	public static final int _hexNumber = 3;
	public static final int maxT = 29;

	static final boolean _T = true;
	static final boolean _x = false;
	static final int minErrDist = 2;

	public Token t;    // last recognized token
	public Token la;   // lookahead token
	int errDist = minErrDist;

	public final Scanner scanner;
	public final Errors errors;
	private final AsmFactory factory;
	private LLVMInlineAssemblyRootNode root;
	private LLVMBaseType retType;


	public Parser(String asmSnippet, String asmFlags, @SuppressWarnings("unused") LLVMExpressionNode[] args, LLVMBaseType retType) {
		this.scanner = new Scanner(new ByteArrayInputStream(asmSnippet.getBytes()));
		errors = new Errors();
		this.factory = new AsmFactory(asmFlags);
		this.retType = retType;
	}

	void SynErr (int n) {
		if (errDist >= minErrDist) errors.SynErr(la.line, la.col, n);
		errDist = 0;
	}

	public void SemErr (String msg) {
		if (errDist >= minErrDist) errors.SemErr(t.line, t.col, msg);
		errDist = 0;
	}

	void Get () {
		for (;;) {
			t = la;
			la = scanner.Scan();
			if (la.kind <= maxT) {
				++errDist;
				break;
			}

			la = t;
		}
	}

	void Expect (int n) {
		if (la.kind==n) Get(); else { SynErr(n); }
	}

	boolean StartOf (int s) {
		return set[s][la.kind];
	}

	void ExpectWeak (int n, int follow) {
		if (la.kind == n) Get();
		else {
			SynErr(n);
			while (!StartOf(follow)) Get();
		}
	}

	boolean WeakSeparator (int n, int syFol, int repFol) {
		int kind = la.kind;
		if (kind == n) { Get(); return true; }
		else if (StartOf(repFol)) return false;
		else {
			SynErr(n);
			while (!(set[syFol][kind] || set[repFol][kind] || set[0][kind])) {
				Get();
				kind = la.kind;
			}
			return StartOf(syFol);
		}
	}

	void InlineAssembly() {

		Expect(4);
		if (la.kind == 7 || la.kind == 8) {
			AddSubOperation();
		} else if (la.kind == 9 || la.kind == 10) {
			IncDecOperation();
		} else if (StartOf(1)) {
			LogicOperation();
		} else if (StartOf(2)) {
			ShiftOperation();
		} else if (la.kind == 19) {
			MoveOperation();
		} else SynErr(30);
		while (StartOf(3)) {
			if (la.kind == 7 || la.kind == 8) {
				AddSubOperation();
			} else if (la.kind == 9 || la.kind == 10) {
				IncDecOperation();
			} else if (StartOf(1)) {
				LogicOperation();
			} else if (StartOf(2)) {
				ShiftOperation();
			} else {
				MoveOperation();
			}
		}
		Expect(4);
		root = factory.finishInline();
	}

	void AddSubOperation() {
		String op; String left = null, right = null;
		op = AddSubOp();
		if (StartOf(4)) {
			left = Register();
			Expect(5);
			right = Register();
		} else if (la.kind == 28) {
			left = Immediate();
			Expect(5);
			right = Register();
		} else SynErr(31);
		Expect(6);
		factory.createBinaryOperation(op, left, right);
	}

	void IncDecOperation() {
		String op; String left = null;
		op = IncDecOp();
		left = Register();
		Expect(6);
		factory.createUnaryOperation(op, left);
	}

	void LogicOperation() {
		String op = null; String left = null, right = null;
		if (la.kind == 11) {
			op = UnaryLogicOp();
			left = Register();
			factory.createUnaryOperation(op, left);
		} else if (la.kind == 12 || la.kind == 13 || la.kind == 14) {
			op = BinaryLogicOp();
			left = Register();
			Expect(5);
			right = Register();
			factory.createBinaryOperation(op, left, right);
		} else SynErr(32);
		Expect(6);
	}

	void ShiftOperation() {
		String op = null; String left = null, right = null;
		op = ShiftOp();
		left = Immediate();
		Expect(5);
		right = Register();
		factory.createBinaryOperation(op, left, right);
		Expect(6);
	}

	void MoveOperation() {
		String op; String left = null, right = null;
		op = MoveOp();
		if (StartOf(4)) {
			left = Register();
			Expect(5);
			right = Register();
		} else if (la.kind == 28) {
			left = Immediate();
			Expect(5);
			right = Register();
		} else SynErr(33);
		Expect(6);
		factory.createBinaryOperation(op, left, right);
	}

	String  AddSubOp() {
		String  op;
		op = la.val;
		if (la.kind == 7) {
			Get();
		} else if (la.kind == 8) {
			Get();
		} else SynErr(34);
		return op;
	}

	String  Register() {
		String  reg;
		switch (la.kind) {
		case 20: {
			Get();
			break;
		}
		case 21: {
			Get();
			break;
		}
		case 22: {
			Get();
			break;
		}
		case 23: {
			Get();
			break;
		}
		case 24: {
			Get();
			break;
		}
		case 25: {
			Get();
			break;
		}
		case 26: {
			Get();
			break;
		}
		case 27: {
			Get();
			break;
		}
		default: SynErr(35); break;
		}
		reg = t.val; factory.addFrameSlot(reg, this.retType);
		return reg;
	}

	String  Immediate() {
		String  n;
		n = null;
		Expect(28);
		if (la.kind == 2) {
			Get();
			n = t.val;
		} else if (la.kind == 3) {
			Get();
			n = t.val;
		} else SynErr(36);
		return n;
	}

	String  IncDecOp() {
		String  op;
		op = la.val;
		if (la.kind == 9) {
			Get();
		} else if (la.kind == 10) {
			Get();
		} else SynErr(37);
		return op;
	}

	String  UnaryLogicOp() {
		String  op;
		op = la.val;
		Expect(11);
		return op;
	}

	String  BinaryLogicOp() {
		String  op;
		op = la.val;
		if (la.kind == 12) {
			Get();
		} else if (la.kind == 13) {
			Get();
		} else if (la.kind == 14) {
			Get();
		} else SynErr(38);
		return op;
	}

	String  ShiftOp() {
		String  op;
		op = la.val;
		if (la.kind == 15) {
			Get();
		} else if (la.kind == 16) {
			Get();
		} else if (la.kind == 17) {
			Get();
		} else if (la.kind == 18) {
			Get();
		} else SynErr(39);
		return op;
	}

	String  MoveOp() {
		String  op;
		op = la.val;
		Expect(19);
		return op;
	}



	public LLVMInlineAssemblyRootNode Parse() {
		la = new Token();
		la.val = "";
		Get();
		InlineAssembly();
		Expect(0);

		if(root == null)
			throw new IllegalStateException();
		return root;
	}

	private static final boolean[][] set = {
		{_T,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_T, _T,_T,_T,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_T, _T,_T,_T,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_T, _T,_T,_T,_T, _T,_T,_T,_T, _T,_T,_T,_T, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _T,_T,_T,_T, _T,_T,_T,_T, _x,_x,_x}

	};

} // end Parser


class Errors {
	public int count = 0;                                    // number of errors detected
	public java.io.PrintStream errorStream = System.out;     // error messages go to this stream
	public String errMsgFormat = "-- line {0} col {1}: {2}"; // 0=line, 1=column, 2=text

	protected void printMsg(int line, int column, String msg) {
		StringBuffer b = new StringBuffer(errMsgFormat);
		int pos = b.indexOf("{0}");
		if (pos >= 0) { b.delete(pos, pos+3); b.insert(pos, line); }
		pos = b.indexOf("{1}");
		if (pos >= 0) { b.delete(pos, pos+3); b.insert(pos, column); }
		pos = b.indexOf("{2}");
		if (pos >= 0) b.replace(pos, pos+3, msg);
		errorStream.println(b.toString());
	}

	public void SynErr (int line, int col, int n) {
		String s;
		switch (n) {
			case 0: s = "EOF expected"; break;
			case 1: s = "ident expected"; break;
			case 2: s = "number expected"; break;
			case 3: s = "hexNumber expected"; break;
			case 4: s = "\"\\\"\" expected"; break;
			case 5: s = "\",\" expected"; break;
			case 6: s = "\";\" expected"; break;
			case 7: s = "\"addl\" expected"; break;
			case 8: s = "\"subl\" expected"; break;
			case 9: s = "\"incl\" expected"; break;
			case 10: s = "\"decl\" expected"; break;
			case 11: s = "\"notl\" expected"; break;
			case 12: s = "\"andl\" expected"; break;
			case 13: s = "\"orl\" expected"; break;
			case 14: s = "\"xorl\" expected"; break;
			case 15: s = "\"shll\" expected"; break;
			case 16: s = "\"shrl\" expected"; break;
			case 17: s = "\"sall\" expected"; break;
			case 18: s = "\"sarl\" expected"; break;
			case 19: s = "\"movl\" expected"; break;
			case 20: s = "\"%eax\" expected"; break;
			case 21: s = "\"%ebx\" expected"; break;
			case 22: s = "\"%ecx\" expected"; break;
			case 23: s = "\"%edx\" expected"; break;
			case 24: s = "\"%esp\" expected"; break;
			case 25: s = "\"%ebp\" expected"; break;
			case 26: s = "\"%esi\" expected"; break;
			case 27: s = "\"%edi\" expected"; break;
			case 28: s = "\"$$\" expected"; break;
			case 29: s = "??? expected"; break;
			case 30: s = "invalid InlineAssembly"; break;
			case 31: s = "invalid AddSubOperation"; break;
			case 32: s = "invalid LogicOperation"; break;
			case 33: s = "invalid MoveOperation"; break;
			case 34: s = "invalid AddSubOp"; break;
			case 35: s = "invalid Register"; break;
			case 36: s = "invalid Immediate"; break;
			case 37: s = "invalid IncDecOp"; break;
			case 38: s = "invalid BinaryLogicOp"; break;
			case 39: s = "invalid ShiftOp"; break;
			default: s = "error " + n; break;
		}
		printMsg(line, col, s);
		count++;
	}

	public void SemErr (int line, int col, String s) {
		printMsg(line, col, s);
		count++;
	}

	public void SemErr (String s) {
		errorStream.println(s);
		count++;
	}

	public void Warning (int line, int col, String s) {
		printMsg(line, col, s);
	}

	public void Warning (String s) {
		errorStream.println(s);
	}

} // Errors


class FatalError extends RuntimeException {

	public static final long serialVersionUID = 1L;

	public FatalError(String s) {
		super(s);
	}
}
