#!/usr/bin/env bash

mx -d --dy /compiler --jdk jvmci unittest -Dgraal.Dump= -Dgraal.PrintGraph=Network -Dwasmtest.watToWasmExecutable=/usr/local/bin/wat2wasm -Dwasmtest.testSourcePath="src/com.oracle.truffle.wasm.test/src/tests" $@
