#!/usr/bin/env bash

if [ $(uname) == "Linux" ]; then
    WAT_TO_WASM=$HOME/.local/bin/wat2wasm
else
    WAT_TO_WASM=/usr/local/bin/wat2wasm
fi

mx -d --dy /compiler --jdk jvmci unittest -Dgraal.Dump= -Dgraal.PrintGraph=Network -Dwasmtest.watToWasmExecutable=$WAT_TO_WASM -Dwasmtest.testSourcePath="src/com.oracle.truffle.wasm.test/src/tests" $@
