name: 💥 Share Native Image Crash Report (svm_err_b_*.md)
description: Share a crash report for GraalVM's Native Image using the generated `svm_err_b_*.md` file
title: "[Native Image] Crash Report"
labels: ["native-image", "crash-report"]

body:
  - type: markdown
    attributes:
      value: |
        For security vulnerabilities, please consult the [GraalVM security policy](https://github.com/oracle/graal/security/policy) and contact the security team directly.

  - type: textarea
    id: describe_issue
    attributes:
      label: Describe the Issue
      description: "Describe the error you encountered with GraalVM's Native Image. Provide a clear and concise description of what happened and what you were trying to achieve."
    validations:
      required: true

  - type: checkboxes
    id: latest_version_check
    attributes:
      label: "Please confirm if you have tested with the latest available version."
      description: "Using the latest version of GraalVM can resolve many issues."
      options:
        - label: "I tried with the latest version of GraalVM. [Latest GraalVM Version](https://www.graalvm.org/downloads/)"
    validations:
      required: true

  - type: textarea
    id: error_report_file
    attributes:
      label: Share the `svm_err_b_*.md` File
      description: "Share to the `svm_err_b_*.md` file generated by the error."
      placeholder: "Attach the error file here."
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: "Provide any additional context or information that might help in diagnosing the issue, such as environmental variables, system settings, or external dependencies."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### How to Find and Share the `svm_err_b_*.md` File

        When a native image build fails fatally, GraalVM generates a detailed error report file with a name like `svm_err_b_<timestamp>_<pid>.md`. This file contains valuable information for diagnosing the issue.

        Use -H:ErrorFile to adjust the path or filename.

        Once located, please attach this file to the issue report. You can also provide a link to the file if it is hosted in a shared location.



