#!/bin/sh

CONFIG_PATH=$1
LLVM_ROOT=$2
BINARYEN_ROOT=$3
EMSCRIPTEN_ROOT=$4
NODE_JS=$5

printf "import os\n" > $CONFIG_PATH
printf "\n" > $CONFIG_PATH
printf "LLVM_ROOT=$LLVM_ROOT\n" >> $CONFIG_PATH
printf "BINARYEN_ROOT=$BINARYEN_ROOT\n" >> $CONFIG_PATH
printf "EMSCRIPTEN_ROOT=$EMSCRIPTEN_ROOT\n" >> $CONFIG_PATH
printf "NODE_JS=$NODE_JS\n" >> $CONFIG_PATH
printf "COMPILER_ENGINE = NODE_JS\n" >> $CONFIG_PATH
printf "JS_ENGINES = [NODE_JS]\n" >> $CONFIG_PATH

echo "Generated Emscripten config file at $CONFIG_PATH:"
echo "--------"
cat $CONFIG_PATH
echo "--------"
