/*
 * Copyright (c) 2026, 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
package com.oracle.svm.configure.test.config;

import static org.junit.Assume.assumeTrue;

import java.nio.file.Paths;

import org.junit.Assert;
import org.junit.Test;

import com.oracle.svm.configure.NamedConfigurationTypeDescriptor;
import com.oracle.svm.configure.UnresolvedAccessCondition;
import com.oracle.svm.configure.config.ConfigurationFileCollection;
import com.oracle.svm.configure.config.ConfigurationMemberInfo;
import com.oracle.svm.configure.config.ConfigurationMethod;
import com.oracle.svm.configure.config.ConfigurationSet;
import com.oracle.svm.configure.config.ConfigurationType;
import com.oracle.svm.configure.config.TypeConfiguration;
import com.oracle.svm.configure.test.AddExports;

/**
 * Verifies the metadata generated by {@link ClassPathJarResourceAgentTest}. This class is separate
 * from the generator so the agent run does not need to load configuration parser types while JUnit
 * discovers the selected generator method.
 */
@AddExports({"org.graalvm.nativeimage/org.graalvm.nativeimage.impl",
                "jdk.graal.compiler/jdk.graal.compiler.util",
                "jdk.graal.compiler/jdk.graal.compiler.util.json"})
public class ClassPathJarResourceAgentVerifierTest {
    private static final String VERIFIER_ENABLED_PROPERTY = ClassPathJarResourceAgentVerifierTest.class.getName() + ".verifier.enabled";
    private static final String CONFIG_PATH_PROPERTY = ClassPathJarResourceAgentVerifierTest.class.getName() + ".configpath";
    private static final String JAR_HANDLER = "sun.net.www.protocol.jar.Handler";

    @Test
    public void verifyJarUrlHandlerMetadataWasNotGenerated() throws Exception {
        assumeTrue("Test must be explicitly enabled because it verifies a previous agent run",
                        Boolean.getBoolean(VERIFIER_ENABLED_PROPERTY));

        TypeConfiguration reflectionConfiguration = loadActualConfig().getReflectionConfiguration();
        Assert.assertNotNull("""
                        The agent did not record the reflection probe, so this verifier is not \
                        checking an agent-generated configuration.""",
                        getConfigurationType(reflectionConfiguration,
                                        ClassPathJarResourceAgentTest.ReflectiveProbe.class.getName()));
        Assert.assertNull("""
                        Classpath resource access through a JAR must not add reflective metadata \
                        for the JDK jar URL handler.""",
                        getConfigurationType(reflectionConfiguration, JAR_HANDLER));
    }

    @Test
    public void verifyJarUrlHandlerMetadataWasGenerated() throws Exception {
        assumeTrue("Test must be explicitly enabled because it verifies a previous agent run",
                        Boolean.getBoolean(VERIFIER_ENABLED_PROPERTY));

        TypeConfiguration reflectionConfiguration = loadActualConfig().getReflectionConfiguration();
        ConfigurationType jarHandlerType = getConfigurationType(reflectionConfiguration, JAR_HANDLER);
        Assert.assertNotNull("""
                        Explicit jar: URL access must add reflective metadata for the JDK jar URL \
                        handler, even if an earlier classpath resource lookup cached the handler.""",
                        jarHandlerType);
        ConfigurationMemberInfo constructorInfo = getConstructorInfo(jarHandlerType);
        Assert.assertNotNull("Missing JDK jar URL handler constructor metadata", constructorInfo);
        Assert.assertEquals("ACCESSED", constructorInfo.getAccessibility().toString());
    }

    private static ConfigurationSet loadActualConfig() throws Exception {
        String configurationPath = System.getProperty(CONFIG_PATH_PROPERTY);
        Assert.assertNotNull("Missing generated configuration path", configurationPath);
        ConfigurationFileCollection configurationFileCollection = new ConfigurationFileCollection();
        configurationFileCollection.addDirectory(Paths.get(configurationPath));
        return configurationFileCollection.loadConfigurationSet(e -> e, null, null);
    }

    private static ConfigurationType getConfigurationType(TypeConfiguration reflectionConfiguration, String className) {
        return reflectionConfiguration.get(UnresolvedAccessCondition.unconditional(),
                        NamedConfigurationTypeDescriptor.fromReflectionName(className));
    }

    private static ConfigurationMemberInfo getConstructorInfo(ConfigurationType configurationType) {
        ConfigurationMethod constructorMethod = new ConfigurationMethod("<init>", "()V");
        return ConfigurationType.TestBackdoor.getMethodInfoIfPresent(configurationType, constructorMethod);
    }
}
