/*
 * Copyright (c) 2026, 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
package com.oracle.svm.configure.test.config;

import static org.junit.Assume.assumeTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

import org.graalvm.collections.EconomicMap;
import org.junit.Assert;
import org.junit.Test;

import com.oracle.svm.configure.NamedConfigurationTypeDescriptor;
import com.oracle.svm.configure.UnresolvedAccessCondition;
import com.oracle.svm.configure.config.ConfigurationFileCollection;
import com.oracle.svm.configure.config.ConfigurationSet;
import com.oracle.svm.configure.config.ConfigurationType;
import com.oracle.svm.configure.config.TypeConfiguration;
import com.oracle.svm.configure.test.AddExports;

import jdk.graal.compiler.util.json.JsonParser;

/** Verifies the metadata and raw trace generated by {@link FieldAccessAgentTest}. */
@AddExports({"org.graalvm.nativeimage/org.graalvm.nativeimage.impl",
                "jdk.graal.compiler/jdk.graal.compiler.util",
                "jdk.graal.compiler/jdk.graal.compiler.util.json"})
public class FieldAccessAgentVerifierTest {
    private static final String VERIFIER_ENABLED_PROPERTY = FieldAccessAgentVerifierTest.class.getName() + ".verifier.enabled";
    private static final String CONFIG_PATH_PROPERTY = FieldAccessAgentVerifierTest.class.getName() + ".configpath";
    private static final String TRACE_PATH_PROPERTY = FieldAccessAgentVerifierTest.class.getName() + ".tracepath";

    @Test
    public void verifyFieldAccessMetadataAndTrace() throws Exception {
        assumeTrue("Test must be explicitly enabled because it verifies previous agent runs",
                        Boolean.getBoolean(VERIFIER_ENABLED_PROPERTY));

        TypeConfiguration reflectionConfiguration = loadActualConfig().getReflectionConfiguration();
        ConfigurationType holderType = getConfigurationType(reflectionConfiguration, FieldAccessAgentTest.FieldHolder.class.getName());
        Assert.assertNotNull("Missing field holder metadata", holderType);
        Assert.assertNull("Looking up a field must not register it for reflective access",
                        ConfigurationType.TestBackdoor.getFieldInfoIfPresent(holderType, FieldAccessAgentTest.QUERIED_FIELD_NAME));
        assertFieldPresent(holderType, FieldAccessAgentTest.ACCESSED_FIELD_NAME);
        assertFieldPresent(holderType, FieldAccessAgentTest.OVERRIDDEN_FIELD_NAME);
        assertFieldPresent(holderType, FieldAccessAgentTest.REFERENCE_FIELD_NAME);
        assertFieldPresent(holderType, FieldAccessAgentTest.INTEGER_FIELD_NAME);
        assertFieldPresent(holderType, FieldAccessAgentTest.LONG_FIELD_NAME);
        assertFieldPresent(holderType, FieldAccessAgentTest.UNSAFE_FIELD_NAME);

        Assert.assertEquals("Each reflective access must emit an accessField event", FieldAccessAgentTest.REFLECTIVE_ACCESS_COUNT,
                        countAccessFieldEvents(FieldAccessAgentTest.ACCESSED_FIELD_NAME));
        Assert.assertEquals("Each override access must emit an accessField event", FieldAccessAgentTest.REFLECTIVE_ACCESS_COUNT + 1,
                        countAccessFieldEvents(FieldAccessAgentTest.OVERRIDDEN_FIELD_NAME));
        Assert.assertEquals(1, countAccessFieldEvents(FieldAccessAgentTest.REFERENCE_FIELD_NAME));
        Assert.assertEquals(1, countAccessFieldEvents(FieldAccessAgentTest.INTEGER_FIELD_NAME));
        Assert.assertEquals(1, countAccessFieldEvents(FieldAccessAgentTest.LONG_FIELD_NAME));
        Assert.assertEquals("sun.misc.Unsafe delegation must not emit a duplicate event", 1,
                        countAccessFieldEvents(FieldAccessAgentTest.UNSAFE_FIELD_NAME, FieldAccessAgentTest.class.getName()));
    }

    private static void assertFieldPresent(ConfigurationType holderType, String fieldName) {
        Assert.assertNotNull("Missing field metadata for " + fieldName,
                        ConfigurationType.TestBackdoor.getFieldInfoIfPresent(holderType, fieldName));
    }

    private static ConfigurationSet loadActualConfig() throws Exception {
        String configurationPath = System.getProperty(CONFIG_PATH_PROPERTY);
        Assert.assertNotNull("Missing generated configuration path", configurationPath);
        ConfigurationFileCollection configurationFileCollection = new ConfigurationFileCollection();
        configurationFileCollection.addDirectory(Paths.get(configurationPath));
        return configurationFileCollection.loadConfigurationSet(e -> e, null, null);
    }

    private static int countAccessFieldEvents(String fieldName) throws Exception {
        return countAccessFieldEvents(fieldName, null);
    }

    @SuppressWarnings("unchecked")
    private static int countAccessFieldEvents(String fieldName, String expectedCallerClass) throws Exception {
        String tracePath = System.getProperty(TRACE_PATH_PROPERTY);
        Assert.assertNotNull("Missing generated trace path", tracePath);
        Path path = Paths.get(tracePath);
        Assert.assertTrue("Missing generated trace file: " + path, Files.isRegularFile(path));
        List<EconomicMap<String, Object>> entries;
        try (var reader = Files.newBufferedReader(path)) {
            entries = (List<EconomicMap<String, Object>>) new JsonParser(reader).parse();
        }

        int count = 0;
        for (EconomicMap<String, Object> entry : entries) {
            if (!"reflect".equals(entry.get("tracer")) || !"accessField".equals(entry.get("function")) ||
                            !FieldAccessAgentTest.FieldHolder.class.getName().equals(entry.get("class"))) {
                continue;
            }
            Object args = entry.get("args");
            if (args instanceof List<?> arguments && arguments.size() == 1 && fieldName.equals(arguments.get(0))) {
                if (expectedCallerClass != null) {
                    Assert.assertEquals("Unexpected accessField caller", expectedCallerClass, entry.get("caller_class"));
                }
                count++;
            }
        }
        return count;
    }

    private static ConfigurationType getConfigurationType(TypeConfiguration reflectionConfiguration, String className) {
        return reflectionConfiguration.get(UnresolvedAccessCondition.unconditional(),
                        NamedConfigurationTypeDescriptor.fromReflectionName(className));
    }
}
