/*
 * Copyright (c) 2026, 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
package com.oracle.svm.configure.test.config;

import static org.junit.Assume.assumeTrue;

import java.nio.file.Paths;
import java.security.Provider;
import java.security.Security;

import org.junit.Assert;
import org.junit.Test;

import com.oracle.svm.configure.NamedConfigurationTypeDescriptor;
import com.oracle.svm.configure.UnresolvedAccessCondition;
import com.oracle.svm.configure.config.ConfigurationFileCollection;
import com.oracle.svm.configure.config.ConfigurationSet;
import com.oracle.svm.configure.config.TypeConfiguration;
import com.oracle.svm.configure.test.AddExports;

/**
 * Verifies the metadata generated by {@link SecurityProviderAgentTest}.
 */
@AddExports({"org.graalvm.nativeimage/org.graalvm.nativeimage.impl",
                "jdk.graal.compiler/jdk.graal.compiler.util",
                "jdk.graal.compiler/jdk.graal.compiler.util.json"})
public class SecurityProviderAgentVerifierTest {
    private static final String VERIFIER_ENABLED_PROPERTY = SecurityProviderAgentVerifierTest.class.getName() + ".verifier.enabled";
    private static final String CONFIG_PATH_PROPERTY = SecurityProviderAgentVerifierTest.class.getName() + ".configpath";

    @Test
    public void verifyEnumeratedProvidersWereRecorded() throws Exception {
        assumeTrue("Test must be explicitly enabled because it verifies a previous agent run",
                        Boolean.getBoolean(VERIFIER_ENABLED_PROPERTY));

        TypeConfiguration reflectionConfiguration = loadActualConfig().getReflectionConfiguration();
        Assert.assertNotNull("""
                        The agent did not record the reflection probe, so this verifier is not \
                        checking an agent-generated configuration.""",
                        reflectionConfiguration.get(UnresolvedAccessCondition.unconditional(),
                                        NamedConfigurationTypeDescriptor.fromReflectionName(SecurityProviderAgentTest.ReflectiveProbe.class.getName())));
        for (Provider provider : Security.getProviders()) {
            String providerClassName = provider.getClass().getName();
            Assert.assertNotNull("Missing reflection metadata for enumerated provider " + providerClassName,
                            reflectionConfiguration.get(UnresolvedAccessCondition.unconditional(),
                                            NamedConfigurationTypeDescriptor.fromReflectionName(providerClassName)));
        }
    }

    @Test
    public void verifyMutationRecordedOnlySuppliedProvider() throws Exception {
        assumeTrue("Test must be explicitly enabled because it verifies a previous agent run",
                        Boolean.getBoolean(VERIFIER_ENABLED_PROPERTY));

        TypeConfiguration reflectionConfiguration = loadActualConfig().getReflectionConfiguration();
        assertRecorded(reflectionConfiguration, SecurityProviderAgentTest.ReflectiveProbe.class.getName());
        assertRecorded(reflectionConfiguration, SecurityProviderAgentTest.ProgrammaticallyAddedProvider.class.getName());
        for (Provider provider : Security.getProviders()) {
            String providerClassName = provider.getClass().getName();
            Assert.assertNull("Provider-list mutation unexpectedly recorded configured provider " + providerClassName,
                            reflectionConfiguration.get(UnresolvedAccessCondition.unconditional(),
                                            NamedConfigurationTypeDescriptor.fromReflectionName(providerClassName)));
        }
    }

    private static void assertRecorded(TypeConfiguration reflectionConfiguration, String className) {
        Assert.assertNotNull("Missing reflection metadata for " + className,
                        reflectionConfiguration.get(UnresolvedAccessCondition.unconditional(),
                                        NamedConfigurationTypeDescriptor.fromReflectionName(className)));
    }

    private static ConfigurationSet loadActualConfig() throws Exception {
        String configurationPath = System.getProperty(CONFIG_PATH_PROPERTY);
        Assert.assertNotNull("Missing generated configuration path", configurationPath);
        ConfigurationFileCollection configurationFileCollection = new ConfigurationFileCollection();
        configurationFileCollection.addDirectory(Paths.get(configurationPath));
        return configurationFileCollection.loadConfigurationSet(e -> e, null, null);
    }
}
