#!/bin/bash

function printUsage() {
    echo "Usage:"
    echo "$0 <GraalVM launcher> <launcher args>"
    echo "Example:"
    echo "$0 js example.js"
    exit 0
}

[ -z "$1" ] || [ "$1" == "--help" ] || [ "$1" == "-help" ] && printUsage

LAUNCHER=$1
shift

"$JAVA_HOME/bin/$LAUNCHER" \
    --jvm \
    --vm.Dtruffle.class.path.append=target/simpletool-20.0.0.jar \
    --simple-code-coverage \
    "$@"
