int main() {
  float f = (float)1.0;
  long l = 1;
  int si = 1;
  unsigned int ui = 1;
  char c = (char)1;
  int sum = 0;
  sum += f <= f;
  sum += l <= l;
  sum += si <= si;
  sum += ui <= ui;
  sum += c <= c;
  sum += f <= l;
  sum += f <= si;
  sum += f <= ui;
  sum += f <= c;
  sum += l <= f;
  sum += l <= si;
  sum += l <= ui;
  sum += l <= c;
  sum += si <= f;
  sum += si <= l;
  sum += si <= si;
  sum += si <= ui;
  sum += si <= c;
  sum += ui <= f;
  sum += ui <= l;
  sum += ui <= si;
  sum += ui <= c;
  sum += c <= f;
  sum += c <= l;
  sum += c <= si;
  sum += c <= ui;
  sum += c <= c;

  c = 0;
  l = 0;
  si = 3;
  sum += f <= f;
  sum += l <= l;
  sum += si <= si;
  sum += ui <= ui;
  sum += c <= c;
  sum += f <= l;
  sum += f <= si;
  sum += f <= ui;
  sum += f <= c;
  sum += l <= f;
  sum += l <= si;
  sum += l <= ui;
  sum += l <= c;
  sum += si <= f;
  sum += si <= l;
  sum += si <= si;
  sum += si <= ui;
  sum += si <= c;
  sum += ui <= f;
  sum += ui <= l;
  sum += ui <= si;
  sum += ui <= c;
  sum += c <= f;
  sum += c <= l;
  sum += c <= si;
  sum += c <= ui;
  sum += c <= c;
  return sum;
}
