source "https://rubygems.org"

gem "jekyll", "~> 4.4.0"

gem "graal-languages-jekyll-theme"

group :jekyll_plugins do
  gem "jekyll-relative-links"
  gem "jekyll-seo-tag"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

# Clean unused resources with `bundle exec siteleaf clean resources`
group :development do
  gem 'siteleaf'
  gem 'pry'
  gem 'html-proofer'
  # Run this with:
  #   bundle exec htmlproofer --swap-urls '^/python/:/' ./_site/
end
