/*
 * Copyright (c) 2024, 2025, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package jdk.graal.compiler.phases.dfanalysis;

import static jdk.graal.compiler.nodeinfo.InputType.Guard;
import static jdk.graal.compiler.nodeinfo.InputType.Unchecked;
import static jdk.graal.compiler.nodeinfo.NodeCycles.CYCLES_0;
import static jdk.graal.compiler.nodeinfo.NodeSize.SIZE_0;

import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.Objects;

import jdk.graal.compiler.debug.DebugContext;
import jdk.graal.compiler.debug.GraalError;
import jdk.graal.compiler.debug.TTY;
import jdk.graal.compiler.graph.Node;
import jdk.graal.compiler.graph.NodeClass;
import jdk.graal.compiler.nodeinfo.NodeInfo;
import jdk.graal.compiler.nodes.AbstractBeginNode;
import jdk.graal.compiler.nodes.NodeView;
import jdk.graal.compiler.nodes.StructuredGraph;
import jdk.graal.compiler.nodes.ValueNode;
import jdk.graal.compiler.nodes.calc.FloatingNode;
import jdk.graal.compiler.nodes.spi.ValueProxy;

/**
 * <p>
 * This node is very similar to the {@link jdk.graal.compiler.nodes.PiNode} in the sense that it
 * encodes additional information about a value in a branch of control flow. InferredFactNodes are
 * intended to be very short-lived. They are inserted by {@link DFAnalysis} to represent additional
 * information about values in certain branches and should get removed again after the analysis
 * concluded by calling {@link DFAnalysis#cleanup}.
 * </p>
 * <p>
 * In addition to the value this node represents and the begin node denoting the control flow branch
 * this node is associated with, this node also retains a reference to its generating node (the
 * condition or switch that caused this node to be created) to verify the graph shape during the
 * course of the analysis to ensure correctness.
 * </p>
 * 
 * @param <LE_TYPE>
 */
@NodeInfo(cycles = CYCLES_0, size = SIZE_0, nameTemplate = "=> ({i#value} in {i#guard})")
public final class InferredFactNode<LE_TYPE> extends FloatingNode implements ValueProxy {
    @SuppressWarnings("rawtypes") public static final NodeClass<InferredFactNode> TYPE = NodeClass.create(InferredFactNode.class);

    private final AnalysisDomainDefinition<LE_TYPE> domain;
    final Class<LE_TYPE> elementType;

    /**
     * The node that caused this inference to be created. This reference is only used to check graph
     * structures this node relies upon to be sure that it actually contains valid information. This
     * node does not actually consume any value generated by the 'generator'. <br />
     * The 'value' input of this node must ALWAYS be a direct input of 'generator' for the
     * information in this node to be trusted.
     */
    @Input(Unchecked) ValueNode generator;

    /**
     * The begin node of the branch this inference is tied to.
     */
    @Input(Guard) AbstractBeginNode guard;

    /**
     * The value for which this inference provides additional information.
     */
    @Input ValueNode value;

    /**
     * The additional information provided by this node.
     */
    private LE_TYPE additionalInformation;

    public InferredFactNode(Class<LE_TYPE> elementType, AnalysisDomainDefinition<LE_TYPE> domain, ValueNode generator, ValueNode value, AbstractBeginNode guard, LE_TYPE elem) {
        super(TYPE, value.stamp(NodeView.DEFAULT));
        this.elementType = Objects.requireNonNull(elementType);
        this.domain = Objects.requireNonNull(domain);
        this.generator = Objects.requireNonNull(generator);
        this.value = Objects.requireNonNull(value);
        this.guard = Objects.requireNonNull(guard);
        GraalError.guarantee(elem != null && !domain.isEqual(domain.unevaluated(elem), elem), "trying to insert inference %s", elem);
        additionalInformation = elem;
    }

    public <OTHER> InferredFactNode<OTHER> tryCast(Class<OTHER> otherGenericType) {
        return isOfGeneric(otherGenericType) ? castTo(otherGenericType) : null;
    }

    /**
     * This method wraps an <b>unchecked</b> cast for ease of use. It expects the user to first
     * check if this cast is possible with {@link InferredFactNode#isOfGeneric(Class)}.
     */
    @SuppressWarnings({"unchecked", "unused"})
    public <OTHER> InferredFactNode<OTHER> castTo(Class<OTHER> other) {
        return (InferredFactNode<OTHER>) this;
    }

    public <OTHER> boolean isOfGeneric(Class<OTHER> otherGenericType) {
        return elementType.equals(otherGenericType);
    }

    public void overrideInformation(LE_TYPE elem) {
        GraalError.guarantee(elem != null && !domain.isEqual(domain.unevaluated(elem), elem), "trying to insert inference %s (previously %s)", elem, additionalInformation);
        additionalInformation = elem;
    }

    @Override
    public AbstractBeginNode getGuard() {
        return guard;
    }

    @Override
    public ValueNode getOriginalNode() {
        return value;
    }

    public LE_TYPE getAdditionalInformation() {
        return additionalInformation;
    }

    public ValueNode getGenerator() {
        return generator;
    }

    boolean matches(Class<?> analysisElementType, AbstractBeginNode analysisGuard, ValueNode analysisValue, ValueNode analysisGenerator) {
        return elementType.equals(analysisElementType) &&
                        guard.equals(analysisGuard) &&
                        value.equals(analysisValue) &&
                        generator.equals(analysisGenerator);
    }

    /**
     * This node effectively works like a {@link jdk.graal.compiler.nodes.PiNode}. It strengthens
     * the information calculated for its input using the additional information of this node. This
     * method assumes this node to be considered reachable by the given analysis. Beware this method
     * can have side effects on the graph.
     *
     * @return result of the transfer function of this node or {@code null} if an error occurred.
     */
    LE_TYPE transfer(DFAnalysis<LE_TYPE> analysis) {
        final StructuredGraph graph = analysis.graph;
        final DFAMap<LE_TYPE> elemMap = analysis.elemMap;

        LE_TYPE stronger = domain.strengthen(elemMap.getOrUnrestricted(getOriginalNode()), getAdditionalInformation());
        /*
         * If the domain provides reasoning for ValueProxies, we want to capture this extra
         * information in addition to the information provided in this node.
         */
        stronger = domain.strengthen(stronger, domain.transfer(this, elemMap));
        if (domain.isUnevaluated(stronger)) {
            GraalError.guarantee(analysis.mayBeReachable(analysis.cfg.blockFor(getGuard())), "The analysis should only ever call InferredFactNode#transfer on reachable nodes");
            /*
             * This InferredFact is reachable despite conflicting stamps. This could be because the
             * inferred value is wrong or because although the given analysis can create a valid
             * inference at this point in the program, it fails to detect this branch as
             * unreachable.
             */
            if (DFAnalysis.Options.DFA_WarnUnreachable.getValue(graph.getOptions()) > 0) {
                int i = 0;
                @SuppressWarnings("unchecked")
                LE_TYPE[] inputs = (LE_TYPE[]) Array.newInstance(elementType, getGenerator().inputs().count());
                for (Node inNode : getGenerator().inputs()) {
                    inputs[i++] = inNode instanceof ValueNode vn ? elemMap.getOrUnrestricted(vn) : null;
                }
                TTY.println("Warning: InferredFactNode#transfer: Inference %s (%s) in branch %s caused by %s with inputs %s " +
                                "should be considered unreachable but the given analysis domain does not allow for such reasoning. Please " +
                                "consider addressing this shortcoming as such circumstances may lower the precision of the analysis.",
                                this, getAdditionalInformation(), getGuard(), getGenerator(), Arrays.toString(inputs));
                if (DFAnalysis.Options.DFA_WarnUnreachable.getValue(graph.getOptions()) > 1) {
                    // also dump a graph to go with the warning
                    analysis.debug.forceDump(graph, "Warning: InferredFactNode#transfer: Inference %s should be unreachable due to inputs %s of %s",
                                    this, Arrays.toString(inputs), getGenerator());
                }
            }

            /*
             * Since this inference should be detected as unreachable but was not, we can not ensure
             * its correctness throughout the rest of the analysis. Therefore, we simply remove it
             * and do not try to infer information at this point in the program again.
             */
            GraalError.guarantee(!elemMap.isEvaluated(this), "Presumably unreachable inference %s was already evaluated", this);
            ValueNode original = Objects.requireNonNull(getOriginalNode());
            replaceAtUsagesAndDelete(original);
            analysis.workList.scheduleUsages(original);
            analysis.debug.dump(DebugContext.VERY_DETAILED_LEVEL, graph, "after dropping inference %s, which should have been unreachable", this);
            return null;
        } else {
            GraalError.guarantee(domain.isWeakerOrEqual(getAdditionalInformation(), stronger).isTrue(),
                            "The result of a strengthening operation should always be at least as strong as its inputs (%s is not stronger than %s)",
                            stronger, getAdditionalInformation());
            return stronger;
        }
    }
}
