/*
 * Copyright (c) 2026, 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
package com.oracle.svm.jvmci.shared.meta;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a method that requires a custom prologue or epilogue for deoptimization.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface DeoptStub {

    /**
     * Custom method prologues and epilogues required for deoptimization. The instructions must be
     * generated by a backend-specific FrameContext class.
     */
    enum StubType {
        NoDeoptStub,

        /**
         * Custom prologue: save all of the architecture's return registers onto the stack.
         */
        EntryStub,

        /**
         * Custom prologue: set the stack pointer to the first method parameter.
         * <p>
         * Custom epilogue: restore all of the architecture's return registers from the stack.
         */
        ExitStub,

        /**
         * Custom prologue: save all ABI registers onto the stack.
         * <p>
         * Custom epilogue: fill in ABI return registers from stack location.
         */
        InterpreterEnterStub,

        /**
         * Custom prologue: adapt incoming JNI arguments to match the wrapper's signature. For
         * varargs calls, we will save all native ABI argument registers onto the stack.
         * <p>
         * Custom epilogue: copy the raw return bits from the general-purpose return register to the
         * floating-point return register.
         */
        InterpreterJNIUpcallStub,

        /**
         * Custom prologue: preserve the incoming native ABI argument registers and caller stack
         * pointer across the isolate transition.
         * <p>
         * Custom epilogue: restore the native ABI return registers from the interpreter's
         * thread-local upcall result data.
         */
        InterpreterFFMUpcallStub,

        /**
         * Custom prologue: store arguments to stack and allocate variable sized frame.
         * <p>
         * Custom epilogue: prepare stack layout and ABI registers for outgoing call.
         */
        InterpreterLeaveStub,

        /**
         * Like {@link #InterpreterLeaveStub}, but calls a native entry point.
         */
        InterpreterNativeDowncallStub,

        /**
         * Custom prologue: move gp return register to first argument register.
         */
        InterpreterDeoptEntryPointStub;

        public boolean isInterpreterStub() {
            return equals(InterpreterEnterStub) || equals(InterpreterJNIUpcallStub) || equals(InterpreterFFMUpcallStub) || equals(InterpreterLeaveStub) || equals(InterpreterNativeDowncallStub);
        }
    }

    StubType stubType();
}
