/*
 * Copyright (c) 2022, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
package org.graalvm.compiler.replacements.amd64;

import static org.graalvm.compiler.core.common.StrideUtil.S1;
import static org.graalvm.compiler.core.common.StrideUtil.S2;

import java.util.EnumSet;

import org.graalvm.compiler.asm.amd64.AVXKind;
import org.graalvm.compiler.core.common.StrideUtil;
import org.graalvm.compiler.core.common.spi.ForeignCallDescriptor;
import org.graalvm.compiler.debug.GraalError;
import org.graalvm.compiler.lir.amd64.AMD64ArrayEqualsOp;
import org.graalvm.compiler.lir.gen.LIRGenerator;
import org.graalvm.compiler.nodes.ValueNode;
import org.graalvm.compiler.replacements.NodeStrideUtil;
import org.graalvm.compiler.replacements.nodes.ForeignCalls;

import jdk.vm.ci.amd64.AMD64;
import jdk.vm.ci.meta.JavaKind;

public final class AMD64ArrayEqualsWithMaskForeignCalls {
    private static final ForeignCallDescriptor STUB_REGION_EQUALS_B_S1_S1_S1 = foreignCallDescriptorByteArray("arrayRegionEqualsBS1S1S1");
    private static final ForeignCallDescriptor STUB_REGION_EQUALS_B_S1_S2_S1 = foreignCallDescriptorByteArray("arrayRegionEqualsBS1S2S1");
    private static final ForeignCallDescriptor STUB_REGION_EQUALS_B_S1_S2_S2 = foreignCallDescriptorByteArray("arrayRegionEqualsBS1S2S2");
    private static final ForeignCallDescriptor STUB_REGION_EQUALS_B_S2_S1_S1 = foreignCallDescriptorByteArray("arrayRegionEqualsBS2S1S1");
    private static final ForeignCallDescriptor STUB_REGION_EQUALS_B_S2_S2_S1 = foreignCallDescriptorByteArray("arrayRegionEqualsBS2S2S1");
    private static final ForeignCallDescriptor STUB_REGION_EQUALS_B_S2_S2_S2 = foreignCallDescriptorByteArray("arrayRegionEqualsBS2S2S2");
    private static final ForeignCallDescriptor STUB_REGION_EQUALS_C = ForeignCalls.pureFunctionForeignCallDescriptor(
                    "arrayRegionEqualsC", boolean.class, char[].class, long.class, char[].class, long.class, char[].class, int.class);
    private static final ForeignCallDescriptor STUB_REGION_EQUALS_DYNAMIC_STRIDES = ForeignCalls.pureFunctionForeignCallDescriptor(
                    "arrayRegionEqualsDynamicStrides", boolean.class, Object.class, long.class, Object.class, long.class, byte[].class, int.class, int.class);
    /**
     * CAUTION: the ordering here is important: entries 0-9 must match the indices generated by
     * {@link NodeStrideUtil#getDirectStubCallIndex(ValueNode, JavaKind, JavaKind)}.
     *
     * @see #getStub(AMD64ArrayRegionEqualsWithMaskNode, LIRGenerator)
     */
    public static final ForeignCallDescriptor[] STUBS = {
                    foreignCallDescriptorObject("arrayRegionEqualsS1S1"),
                    foreignCallDescriptorObject("arrayRegionEqualsS1S2"),
                    foreignCallDescriptorObject("arrayRegionEqualsS1S4"),
                    foreignCallDescriptorObject("arrayRegionEqualsS2S1"),
                    foreignCallDescriptorObject("arrayRegionEqualsS2S2"),
                    foreignCallDescriptorObject("arrayRegionEqualsS2S4"),
                    foreignCallDescriptorObject("arrayRegionEqualsS4S1"),
                    foreignCallDescriptorObject("arrayRegionEqualsS4S2"),
                    foreignCallDescriptorObject("arrayRegionEqualsS4S4"),

                    STUB_REGION_EQUALS_DYNAMIC_STRIDES,

                    STUB_REGION_EQUALS_B_S1_S1_S1,
                    STUB_REGION_EQUALS_B_S1_S2_S1,
                    STUB_REGION_EQUALS_B_S1_S2_S2,
                    STUB_REGION_EQUALS_B_S2_S1_S1,
                    STUB_REGION_EQUALS_B_S2_S2_S1,
                    STUB_REGION_EQUALS_B_S2_S2_S2,

                    STUB_REGION_EQUALS_C,
    };

    private static ForeignCallDescriptor foreignCallDescriptorObject(String name) {
        return ForeignCalls.pureFunctionForeignCallDescriptor(name, boolean.class, Object.class, long.class, Object.class, long.class, byte[].class, int.class);
    }

    private static ForeignCallDescriptor foreignCallDescriptorByteArray(String name) {
        return ForeignCalls.pureFunctionForeignCallDescriptor(name, boolean.class, byte[].class, long.class, byte[].class, long.class, byte[].class, int.class);
    }

    @SuppressWarnings("unchecked")
    public static ForeignCallDescriptor getStub(AMD64ArrayRegionEqualsWithMaskNode node, LIRGenerator gen) {
        JavaKind strideA = node.getStrideA();
        JavaKind strideB = node.getStrideB();
        JavaKind strideM = node.getStrideMask();
        ValueNode length = node.getLength();
        int directStubCallIndex = node.getDirectStubCallIndex();
        GraalError.guarantee(-1 <= directStubCallIndex && directStubCallIndex < 9, "invalid direct stub call index");
        if (directStubCallIndex >= 0 && length.isJavaConstant() &&
                        AMD64ArrayEqualsOp.canGenerateConstantLengthCompare(gen.target(),
                                        (EnumSet<AMD64.CPUFeature>) node.getRuntimeCheckedCPUFeatures(),
                                        StrideUtil.getConstantStrideA(directStubCallIndex),
                                        StrideUtil.getConstantStrideB(directStubCallIndex),
                                        length.asJavaConstant().asInt(), (AVXKind.AVXSize) gen.getMaxVectorSize(node.getRuntimeCheckedCPUFeatures()))) {
            // Yield constant-length arrays comparison assembly
            return null;
        }
        switch (node.getArrayKind()) {
            case Byte:
                switch (strideA) {
                    case Byte:
                        switch (strideB) {
                            case Byte:
                                GraalError.guarantee(strideM == S1, "mask stride must match strideA and strideB");
                                return STUB_REGION_EQUALS_B_S1_S1_S1;
                            case Char:
                                switch (strideM) {
                                    case Byte:
                                        return STUB_REGION_EQUALS_B_S1_S2_S1;
                                    case Char:
                                        return STUB_REGION_EQUALS_B_S1_S2_S2;
                                    default:
                                        throw GraalError.shouldNotReachHere();
                                }
                            default:
                                throw GraalError.shouldNotReachHere();
                        }
                    case Char:
                        switch (strideB) {
                            case Byte:
                                GraalError.guarantee(strideM == S1, "mask stride must match strideA and strideB");
                                return STUB_REGION_EQUALS_B_S2_S1_S1;
                            case Char:
                                switch (strideM) {
                                    case Byte:
                                        return STUB_REGION_EQUALS_B_S2_S2_S1;
                                    case Char:
                                        return STUB_REGION_EQUALS_B_S2_S2_S2;
                                    default:
                                        throw GraalError.shouldNotReachHere();
                                }
                            default:
                                throw GraalError.shouldNotReachHere();
                        }
                    default:
                        throw GraalError.shouldNotReachHere();
                }
            case Char:
                GraalError.guarantee(strideA == S2 && strideB == S2 && strideM == S2, "only stride2 allowed for char arrays");
                return STUB_REGION_EQUALS_C;
            case Void:
                return directStubCallIndex < 0 ? STUB_REGION_EQUALS_DYNAMIC_STRIDES : STUBS[directStubCallIndex];
            default:
                throw GraalError.shouldNotReachHere();
        }
    }
}
