[package]
name = "tregex-casefolding"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
error-chain = "0.12.4"
icu_collator = "1.3.2"
icu_locid = "1.3.2"
indicatif = "0.17.7"
oracle = "0.5.7"
reqwest = { version = "0.11.22", features = ["blocking", "gzip"] }
